bcgov/ECC-ECER

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantContent.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearContent.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearContent.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ExpandSelect.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/CertificationType.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/certification-types.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/expand-select.ts
- ExpandSelect component for "radio panels"
- Components for ECEAssistant, ECEOneYear and ECEFiveYear content
> ECER-785: Select Certification Type

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearContent.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ExpandSelect.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/CertificationType.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/certificationType.ts
- Addressed QA issue to show ITE and SNE options before Five Year certification type selection
- Pinia store for the state certification type selection
- [ECER-712]()
> ECER-712: Show ITE and SNE options under ECE Five Year panel

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRequirements.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearContent.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ExpandSelect.vue
ECER-712: Addressing feedback on certificate selection screen. More spacing in mobile view for the checkboxes and also fixed label styling. 
ECER-882: Updating the title based on certificate type and adding in missing point for 5 year certificates. Also fixed a big with the mobile view squishing the title to be too close.
> ECER-712: certification selection feedback

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationType.vue
ECER-{1013}: Adding error messaging for certification types and preventing user from progressing without filling in all fields.
error
> error message for certification types

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationType.vue
ECER-1013
Quick bug fix so that user wouldn't be able to progress to the next step without choosing a certificate type first. If user enters this page without a certificate type (first time entry or saved draft with empty certificate type) we will default to ECE assistant.
> quick bug fix

- src/ECER.Managers.Registry/ApplicationHandlers.cs
- src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs
- src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
- src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs
ECER-1292: The user should be able to create just one draft application
- Revise the application handler to block the creation of new draft applications if the user already has an existing draft. 
- Update the integration tests to focus solely on testing the update functionality for draft applications within the application endpoint tests.
- ECER-1292
> ECER-1292: The user should be able to create just one draft application

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/application.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ConfirmationDialog.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Snackbar.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WorkExperienceReferenceProgressBar.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/confirmation-dialog.d.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs
ECER-{1110}: Adding frontend changes for cancel application. Also fixed an issue where we were passing Id instead of ApplicationId to the frontend. Breaking our alert boxes (this was introduced in a previous commit I did)
> ECER-1110 Cancel Application FE

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Form.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationType.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts
ECER-1013: Brief description of the changes
- Certificate form doesn't auto select a certification **(ECER-1013)**
- Bug fix where applicant could click back and forward to avoid form validation **(ECER-812)**. Added a v-if on forms to ensure they get remounted each time we travel through the stepper. 
- Updated wording for education checkbox **(ECER-716)**
- Alert box for duplicated character reference in work experience reference. **ECER-1040**
- Bug fix forms would fire off validation when switching between stepper. Showing error messages right away when we first arrive to the forms. (Had to do some setTimeout resetvalidation to prevent this jankiness. 
- Bug fix character reference doesn't get cleared out when user removes first name, last name and email. 
Screenshots 
Alert Box and …
> removing auto selection of certificate type. In exchange, error message pops up right away on new application + other bug fixes

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProfileForm.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationType.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue
ECER-{###}: Refactored how we validate our forms while going through the stepper. Now we do not validate the next form in the sequence. 
Also removed updated-formvalidation emit since we are getting validation directly from the form. 
Removed type=submit for buttons with this refactor.
> changing to use refs to validate form instead of submit buttons

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ConfirmationDialog.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/confirmation-dialog.d.ts
ECER-967: Preview application prior to submission, print functionality
- Added Print Preview button and hooked it up to Print Preview with the browser
- Clicking on "Print Preview" displays a warning message if there is missing data to be filled in the wizard 
- ECER-967
- ECER-1052
Code changes for both - ECER-967 and ECER-1052
> ECER-967 - Preview application prior to submission, print functionality

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Form.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/formInput.ts
ECER-1676: removing toggles when inputting phone number. 
- see above
> fix for toggles to show up on character reference phone number

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Form.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WizardHeader.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/formInput.ts
ECER-1674: 
- Wizard header reflects the certification type.
> bug fix for certification type to reflect in wizard header

- .gitignore
- src/ECER.Clients.Api/Properties/launchSettings.json
- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Properties/launchSettings.json
- src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
Protection key problem solved
ECER-992: Protection key problem solved
- Using the same key for encryption and decryption in API and Registry Backend Projects
- Links to applicant/application/workexperience reference added to portal invitation test
- etc.
- ECER-922
> ECER-992: Protection key problem solved

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue
ECER-1041: rework character reference
bug fix that allowed e and . to be placed into a phone number field.
> bug fix for phone number in character reference accepting e and .

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs
- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- src/ECER.Managers.Registry.Contract/Applications/Contract.cs
- src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs
- src/ECER.Resources.Documents/Applications/IApplicationRepository.cs
- src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs
- src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs
- src/ECER.Tests/Unit/ApplicationSubmissionValidationEngineTests.cs
Move checkboxes from education list to inside education entry
---
This PR aims at moving the education list to inside education entry
ECER-{1758}: Move checkboxes from education list to inside education entry
- Expose ecer_IsECEAssistant in endpoint and map to dynamics
- Expose ecer_DoesECERegistryHaveTranscript in endpoint and map to dynamics
- Expose ecer_IsOfficialTranscriptRequested in endpoint and map to dynamics
- FE - Move checkboxes from education list to inside education entry
- ECER-{716}
- ECER-{1757}
- ECER-{1758}
Added to:
Validation:
Removed from:
> ECER-1758: Move checkboxes from education list to inside education entry

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceDeclaration.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDeclaration.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/config.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/constant.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/functions.ts
- add **before** on declaration page so the sentence makes sense.
- parent **OR** guardian dropdown option
- sort provinces alphabetically while keeping Other at the bottom.
- lower case ECE certification **i**nformation
- period at the end of requesting a character reference for an ECE
-sync up work reference and character reference. Do not bold the name. Add minor spelling changes.
-Change this in label text for certification number:
If you are registered as an ECE in Canada, please provide your certification number if applicable. 
To:
If you're registered as an ECE in Canada, please provide your certification number.
> minor bug fixes after feedback received

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WizardHeader.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationType.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationTypePreview.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducationPreview.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceDeclaration.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/constant.ts
ECER-{1914}: Bug fix where user was able to submit application without meeting the required number of educations. 
- Changed references to CertificationTypes to a constant enum. 
- Made it so SNE and ITE required an additional education transcript to be submitted. This matches the backend validation logic. 
ex. One Year = 1 education required 
Five Year + SNE = 2 
Five Year + ITE = 2 
Five Year + ITE + SNE = 3
> fixing education input error and changing variables to a single constant

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceEvaluation.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceEvaluationPreview.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContactPreview.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceAssessmentPreview.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceEvaluationPreview.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/ReferencePreviewCard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/character-reference-wizard.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/work-experience-reference-review-form.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/work-experience-reference-wizard.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/format.d.ts
---
name: ECER-1214: F.E: Work Experience Reference can preview their responses before submitting.
about: F.E: Work Experience Reference can preview their responses before submitting.
---
ECER-1214: F.E: Work experience reference submission - Preview page
- F.E: Work Experience Reference can preview their responses before submitting.
- F.E: Work Experience Reference can preview their responses before submitting. - error handling
- Work Experience Reference must be able to check-off a declaration
- ECER-1214
- ECER-1271
> ECER-1214: F.E: Work Experience Reference can preview their responses before submitting.

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ActionCard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Alert.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UnreadMessages.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
- Extend ActionCard for content slot
- Extend Alert for full screen on mobile
- Add unread message notification(s) on dashboard
- [ECER-1750](https://eccbc.atlassian.net/browse/ECER-1750)
> ECER-1750: Add unread message notification(s) on dashboard

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/PortalInvitations/PortalInvitationsEndpoints.cs
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDeclaration.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceEvaluation.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- src/ECER.Managers.Registry.Contract/PortalInvitations/Contract.cs
- src/ECER.Managers.Registry/PortalInvitationHandlers.cs
- src/ECER.Managers.Registry/PortalInvitationMapper.cs
---
name: ECER-869 : Work reference must be able to complete work experience hours information
about: Work reference must be able to complete work experience hours information
---
ECER-869: Work reference must be able to complete work experience hours information
- FE: bind value to BE - Applicant indicated you observed them work: %number entered by applicant% hours
- work experience reference -> Declaration page corrections
- ECER-869
- ECER-2080
> ECER-869 : Work reference must be able to complete work experience hours information

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/PreviewCard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducationPreview.vue
ECER-1933: Bugfix for indentation oddities in preview screen
- Made it so titles aren't indented forwards
- Also made it so the first line for work experience + education isn't indented. 
- Tested for mobile + error states
Before (Note indented first line for transcripts/work experience reference
After
Multiple Refrences
Mobile
> fixing indentation issues in preview screens

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Banner.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Invalid.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/ecer-theme.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/apiResultHandler.ts
- src/ECER.Managers.Registry/PortalInvitationHandlers.cs
- src/ECER.Tests/Integration/RegistryApi/PortalInvitationTests.cs
- src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
- Check for existence of associated applicant, application and portal invitation 
- Check status of portal invitation to return 400 for invalid states
- Banner component
- /invalid-reference page
- Redirect to /invalid reference page when token verification fails
- Adjusted portal error handling to display 'detail' field if present
- [ECER-1305](https://eccbc.atlassian.net/browse/ECER-1305)
> ECER-1305: Handle invalid portal invitations

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UnreadMessages.vue
---
name: ECER-2096 - [num] unread message on dashboard is not in bold 
about: Fix for ECER-2096 - [num] unread message on dashboard is not in bold
---
ECER-2096 - [num] unread message on dashboard is not in bold 
- Fix for  [num] unread message on dashboard is not in bold
- ECER-2096
1 unread message:
more than 1 unread message:
> ECER-2096 - [num] unread message on dashboard is not in bold - Fix

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs
- src/ECER.Resources.Documents/Applications/ApplicationRepository.cs
- src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs
- src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
---
name: ECER-2165 : BE: Extend update reference endpoints to allow for new submissions
about: BE: Extend update reference endpoints to allow for new submissions
---
ECER-2165 : BE: Extend update reference endpoints to allow for new submissions
- Extended update reference endpoints to allow for new reference submissions
- Added new automated tests for adding new references
- ECER-2165
- ECER-1852
> ECER-2165 : BE: Extend update reference endpoints to allow for new submissions

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- src/ECER.Managers.Registry.Contract/Applications/Contract.cs
---
name: ECER-2100 - Show manage application option on dashboard for applications under investigation
about: Show manage application option on dashboard for applications under investigation
---
ECER-2100 - Show manage application option on dashboard for applications under investigation
- Added "Pending" and "Escalated" status to "get application status" in the BE
- npm run gen-api
- added required application status checks in the FE.
- added "Pending" and "AppealDecision" to ApplicationStatusSubDetailMaps in ApplicationSummary.vue to fix type-check problems causing build failure.
- ECER-2100
- ECER-1379
"Manage Application" visible on Application status -> "Pending":
> ECER-2100 - Show manage application option on dashboard for applications under investigation

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertCharacterReference.vue
---
name: ECER-2207 - Only mention work reference on character reference form when there application requires work experience
about: Only mention work reference on character reference form when there application requires work experience
---
ECER-2207 - Only mention work reference on character reference form when there application requires work experience
- FE: Conditionally show text based on application type
- ECER-2207
- ECER-2232
Text not visible for "One Year" certification type:
Text visible for "Five Year" certification type:
> ECER-2207 - Only mention work reference on character reference form when there application requires work experience

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Alert.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertCharacterReference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertWorkExperienceReference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts
---
name: ECER-2197: Add validation to new references being added after application submitted to ensure they're different
about: Add validation to new references being added after application submitted to ensure they're different
---
ECER-2197: Add validation to new references being added after application submitted to ensure they're different
- Added checks to prevent duplicate references
- Updated application.ts to remove check for email address while checking for duplicate references
- Added and configured alert component for upsert character and work exp references 
- Alert component is configured as:
- Alert with the error summary should got at the top of the page 
- On submit, it will auto scroll user to the top of the page
- Alert can be dismissed by the user by tapping on the x
- …
> ECER-2197: Add validation to new references being added after application submitted to ensure they're different

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Communications/CommunicationsEndpoints.cs
- src/ECER.Managers.Registry.Contract/Communications/Contract.cs
- src/ECER.Managers.Registry/CommunicationHandlers.cs
- src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs
- src/ECER.Resources.Accounts/Communications/CommunicationRepositoryMapper.cs
- src/ECER.Resources.Accounts/Communications/ICommunicationRepository.cs
- src/ECER.Tests/Integration/RegistryApi/CommunicationTests.cs
- src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
---
name: Backend piece for communication
---
ECER-1254: Add from field to GET child and parent message endpoints
ECER-2316: Create endpoint to get child communication(s) by ecer_parentcommunicationid
ECER-2317: Update messages endpoint to return only parent-level communication records
- Messages endpoint modified to support both parent and child messages
- From field added to communication mapper
- etc.
- ECER-1254
- ECER-2316
- ECER-2317
- etc.
> ECER-2316- ECER-2317- ECER-1254: Backend piece for communication

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/TermsOfUse.vue
ECER-2148: Update to terms of use
- Changed link text to BC Services Card Account Terms of Use
- Changed where the link goes
- Removed sentence  “You acknowledge that you are responsible for all activities that occur using your BCeID or BC Services Card and your Digital Identity, whether those activities were performed by you or someone else.”
> updating terms of use

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.json
- src/ECER.Utilities.Hosting/SecurityExtensions.cs
ECER-1596: This should remove the error when loading the iframe for recaptcha on the website. 
- Adding in FrameSource to CspSettings.
Unable to test until this is deployed.
Error message in console.
> adding in frame source for recaptcha

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Communications/CommunicationsEndpoints.cs
- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Files/FilesEndpoints.cs
- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Program.cs
- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.json
- src/ECER.Managers.Registry/ECER.Managers.Registry.csproj
- src/ECER.Tests/Integration/RegistryApi/FileTests.cs
ECER-2328: support file upload backend with automated test
- Upload file endpoint added to registry project
- Uploader with multipart file handler added
- Automated test added for file upload endpoint
VPN Required to run automated test and upload file to S3
- ECER-2328
- ECER-2386
> ECER-2387: Upload file to BE endpoint object storage upload

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/message.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ReplyToMessage.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
---
name: ECER-2258 - FE: Create reply to message page and expose in header on message list view
about: FE: Create reply to message page and expose in header on message list view
---
ECER-2258 - FE: Create reply to message page and expose in header on message list view
- Added FE piece for sending messages
- Connect FE to BE for sending messages
- Added required validations
- Added required page redirections
- ECER-2258
- ECER-1252
> ECER-2258 - FE: Portal User can Reply to messages sent from Registry.

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/application.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/message.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/reference.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/apiResultHandler.ts
- Refactor api handler `execute` function for optional named parameters
- Suppress error for `getReference` api call
- [ECER-1305](https://eccbc.atlassian.net/browse/ECER-1305)
> ECER-1305: Suppress error toast for getReference call (REWORK)

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationCard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/certification.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/_colors.scss
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/ecer-theme.ts
- Handle different certification statuses
- New grey colour for chip
- [ECER-2312](https://eccbc.atlassian.net/browse/ECER-2312)
- [ECER-2313](https://eccbc.atlassian.net/browse/ECER-2313)
- [ECER-2314](https://eccbc.atlassian.net/browse/ECER-2314)
> ECER-2312, ECER-2313 and ECER-2314: Certification statuses

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- src/ECER.Managers.Registry.Contract/Applications/Contract.cs
- src/ECER.Resources.Documents/Applications/IApplicationRepository.cs
- src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs
---
name: ECER-2577: BE: Convert stage field on Application from PortalStage to String
about: BE: Convert stage field on Application from PortalStage to String
---
ECER-2577: BE: Convert stage field on Application from PortalStage to String
- Convert stage field on Application from PortalStage to String -> updated in all layers
- Adjusted application tests
- "npm run gen-api" to reflect changes to openapi spec.
- ECER-2577
- ECER-1172
> ECER-2577: BE: Convert stage field on Application from PortalStage to String

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/certification.ts
- Adjust renewal logic to allow for cancelled certificates to be renewed
- Styling for ECER-2676
- [ECER-2405](https://eccbc.atlassian.net/browse/ECER-2405)
- [ECER-2406](https://eccbc.atlassian.net/browse/ECER-2406)
- [ECER-2407](https://eccbc.atlassian.net/browse/ECER-2407)
- [ECER-2408](https://eccbc.atlassian.net/browse/ECER-2408)
- [ECER-2409](https://eccbc.atlassian.net/browse/ECER-2409)
- [ECER-2410](https://eccbc.atlassian.net/browse/ECER-2410)
> ECER-2406: Allow for cancelled certifications to be renewed (REWORK)

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/FileUploader.vue
ECER-2378: Allow user to upload the same file twice
- Issue was that the value of the v-file-input component was not clearing the value between uploads. When it sees the same value for the next upload it doesn't register. 
> rework allow user to delete and upload the same file twice

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Users/ProfileEndpoints.cs
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/AddPreviousName.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- src/ECER.Managers.Registry.Contract/Registrants/Contract.cs
- src/ECER.Resources.Accounts/Registrants/IRegistrantRepository.cs
- src/ECER.Resources.Accounts/Registrants/RegistrantRepositoryMapper.cs
ECER-2507: Receive Previous Name Record from Portal Submission
- Added and mapped ecer_Source choice field(enum) for Previous Name record in all the layers of B.E
- Setting ecer_Source = "Profile" when adding previous name from  "My profile" section 
- ECER-2507
> ECER-2507: Receive Previous Name Record from Portal Submission

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Users/ProfileEndpoints.cs
- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Users/UserMapper.cs
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/VerifyPreviousName.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- src/ECER.Managers.Registry.Contract/Registrants/Contract.cs
- src/ECER.Managers.Registry/RegistrantMapper.cs
- src/ECER.Resources.Accounts/Registrants/IRegistrantRepository.cs
- src/ECER.Resources.Accounts/Registrants/RegistrantRepository.cs
- src/ECER.Resources.Accounts/Registrants/RegistrantRepositoryMapper.cs
ECER-2245: Upload ID for previous name
- B.E piece for file upload and move to permanent location.
- B.E changes to add uploaded files to bcgov_DocumentUrl dynamics entity and associate with previous name record 
- Updating existing previous name record and setting StatusCode = ecer_PreviousName_StatusCode.ReadyforVerification
- F.E changes for the verify previous name page
- Implemented uploaded file validations
- ECER-2468
- ECER-2469
- ECER-2470
- ECER-2245
No file added:
> ECER-2245: Upload ID for previous name

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-five-year-expired-more-than-five-years-review-form.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-five-year-expired-more-than-five-years.ts
ECER-2996: 5 year expired for more than 5 years flow
- 5 years renewal more than 5 year flow. 
- Removed unused method in application.vue
- ECER-2996
- 
> five years expired for more than 5 years flow renew

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/FileUploader.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceProfessionalDevelopment.vue
- Add optional props with defaults to FileUploader component
- Only allow 1 file uploaded for Professional Development before hiding the "+ Add File" button
- [ECER-1186](https://eccbc.atlassian.net/browse/ECER-1186)
> ECER-1186: Limit file upload to one file for professional development

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Profile.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/user.ts
Filter previous names on portal profile page
- Filter previous names on portal profile page to not include previous names with Source == "NameLog" 
- ECER-{###}
- etc.
> Filter previous names on portal profile page

- src/ECER.Managers.Registry/CommunicationHandlers.cs
- src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs
- src/ECER.Resources.Accounts/Communications/ICommunicationRepository.cs
ECER-3178: The number of messages is not match the number of messages shown
This occurs because Dynamics generates certain messages that are not root messages and do not have a parent communication, so they are not displayed on the messages page. Here are a few examples:
```
{37b1c37e-ce7a-ef11-ac21-000d3a09e82b}
{0c047c81-ce7a-ef11-ac20-6045bdcce125}
{9151bc04-ba7a-ef11-ac21-6045bdcd6cb0}
{6c2f8da5-ec79-ef11-ac20-7c1e5240b0bf}
```
I've separated communication status query function in repository to improve performance as well
> ECER-3178: Status Query for communication separated in Repository

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
but user store stores it as an empty string instead
- Bug found during smoke testing. 
- Cause was that the legal name for an applicant would be gotten as "", however the education names are stored as null. So for the previous radio option generation, it wouldn't find the exact match for the index. 
- index would be -1 and when we try to access that, it's unhappy
> quick fix edit education where middle name could be null 

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducationPreview.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceProfessionalDevelopment.vue
ECER-1186: Brief description of the changes
- quick fix for + icon
- black text for education preview
> small fix removing + icon on save course or workshop

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/.vscode/extensions.json
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/LookupCertification.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/LookupCertificationRecord.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/lookupCertification.ts
ECER-3210: Display registrant details with terms and conditions
- Displaying registrant details with terms and conditions
- Displaying list of conditions(ecer_details) in order specified by ecer_displayorder
- Displaying registration status as "status chips"
- Adjusted lookup certification store to get Certificate Level Name from store
- ECER-3210
- ECER-3208
**Mobile View:**
> ECER-3210: Display registrant details with terms and conditions

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Files/FilesEndpoints.cs
- src/ECER.Managers.Registry.Contract/Certifications/Contract.cs
- src/ECER.Resources.Documents/Certifications/CertificationRepositoryMapper.cs
- src/ECER.Resources.Documents/Certifications/ICertificationRepository.cs
ECER-3373: Portal certificate download not opening newest certificate file
- Fix for Portal certificate download not opening newest certificate file
- BE : Added and Mapped "Tag1Name" and "CreatedOn" props for Certificate Files 
- Filtering Certificate Files to get latest certificate where Tag 1 Name is "Certificate"
- ECER-3373
> ECER-3373: Portal certificate download not opening newest certificate file

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs
- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- src/ECER.Managers.Registry.Contract/Applications/Contract.cs
- src/ECER.Resources.Documents/Applications/ApplicationRepository.cs
- src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs
- src/ECER.Resources.Documents/Applications/IApplicationRepository.cs
- src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs
ECER-3353: Hide option to continue application for manually entered applications
- BE: (one way) map application origin from dynamics to portal
- BE: Set default application origin to "Portal" in the application repository
- BE: Update automated tests
- FE: Hide "Open application" and "Cancel application" option for manual applications
- ECER-3353
- ECER-3435
- ECER-3436
- ECER-3437
- ECER-3438
> ECER-3353: Hide option to continue application for manually entered applications

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue
- Default to 500 hours when WE reference status list is null
- [ECER-3547](https://eccbc.atlassian.net/browse/ECER-3579)
> ECER-3547: Default to 500 hours

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceDateInput.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue
- `EceDateInput` adjustment for locale
- Spacing adjustment
- Missed styling in reference flows from ECER-2891
- [ECER-2891](https://eccbc.atlassian.net/browse/ECER-2891)
- [ECER-3464](https://eccbc.atlassian.net/browse/ECER-3464)
> ECER-3464: Character Reference Instruction spacing issue

- src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs
- src/ECER.Utilities.DataverseSdk/Model/Entities/bcgov_DocumentUrl.cs
- src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_CertificateSummary.cs
- src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_Investigation.cs
- Add `bcgov_OriginCode` and `ecer_DocumentInternallyReviewed` field defaults
- [ECER-3672](https://eccbc.atlassian.net/browse/ECER-3672)
> ECER-3672: Add field constants to documenturl's created from communication

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue
[ECER-3277](https://eccbc.atlassian.net/browse/ECER-3277)
- showing the back button on reference screens. 
- It was hidden behind the blue banner
> fix back button missing on reference pages

- src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs
- src/ECER.Resources.Documents/Certifications/CertificationRepository.cs
- src/ECER.Tests/Integration/RegistryApi/CertificationTests.cs
- src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
- src/ECER.Tests/Integration/Resources/Certifications/CertificationsRepositoryTests.cs
- Added test with inactive certification record
- Sort by StatusCode first (Active)
- Set default PortalStage if not present in dynamics for applications that start as application origin 'Manual' but transitioned to 'Portal'
- [ECER-2702](https://eccbc.atlassian.net/browse/ECER-2702)
- [ECER-2616](https://eccbc.atlassian.net/browse/ECER-2616)
> ECER-2702: New logic for certification query

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
- Clear stores when oidc `getUser()` returns `null`
- [ECER-3530](https://eccbc.atlassian.net/browse/ECER-3530)
> ECER-3530: Reset sensitive data when we don't have an OIDC session

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/lookupCertification.ts
ECER-3973: Bug fix incorrect status text for 5 yr cert + SNE
- name generation wasn't checking for ITE status. Small fix. 
*before*
*after fix*
> bug fix for registration 5yr + SNE not showing the correct text

- src/ECER.Resources.Documents/Certifications/CertificationRepositoryMapper.cs
ECER-3952: inactive certification conditions filtered out in public lookup
> ECER-3952: inactive certification conditions filtered out in public lookup

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRenewalRequirements.vue
ECER-3993: Renewal for 1year certificate link redirects to new 5 year… certificate
> ECER-3993: Renewal problem

- src/ECER.Managers.Registry/ECER.Managers.Registry.csproj
- src/ECER.Managers.Registry/RegistrantHandlers.cs
- src/ECER.Tests/Integration/RegistryApi/UserInfoTests.cs
https://eccbc.atlassian.net/browse/ECER-3933 
- Issue with Bceid users registering with an invalid country code. 
- Fix was to just save countryName as empty so the user can update it the next time they edit their profile or start a new application. 
- May be difficult to test because our test bceid users have a valid country code. 
> fix for issue if country code doesn't exist in our database

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/AddProfessionalDevelopment.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Profile.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewCharacterReference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewWorkExperienceReference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceProfessionalDevelopment.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/character-references-upsert-form.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/profile-information-form.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/work-experience-reference-upsert-form.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/formRules.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/format.ts
ECER-1746: (Enhancement) Accept international phone numbers
Update validation to all phone number fields to accept 7 to 20 digits or spaces, dashes or plus symbol.
-Update error message from:
Enter a 10-digit phone number
-When required, and field is empty, on submit show:
Enter a phone number
-When a value is entered in the field, and it's less than 7 or more than 20, on submit show:
Enter a valid phone number
This update is applied in:
- In creating an account (BCSC and BCeID)
- In contact form
- In edit profile
- In reference collection in application
- In reference forms
- ECER-1746
On "Edit Profile" page:
Errors out on entering more than 20 characters. Accepts spaces, dashes or plus symbol (in the beginning)
Errors out on entering less than 7 characters. Accepts spaces, dashes or …
> ECER-1746: (Enhancement) Accept international phone numbers

- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/ConfigurationEndpoints.cs
- src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/ConfigurationMapper.cs
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/configuration.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceAddress.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/config.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/form.d.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/formRules.ts
- src/ECER.Managers.Admin.Contract/Metadatas/Contract.cs
- src/ECER.Resources.Documents/MetadataResources/IMetadataResourceRepository.cs
- src/ECER.Resources.Documents/MetadataResources/MetadataResourceRepositoryMapper.cs
- src/ECER.Tests/Integration/RegistryApi/ConfigurationTests.cs
ECER-3095: Accept international addresses and save province name from standard list
Changes apply to home address and mailing address.
Show list of countries
--- Use Autocomplete vuetifyjs component (see links)
--- Comes from ecer_country in dynamics (ECER-3180)
--- Does NOT include 'Other'
--- Default value to Canada if no value already set
If Country = Canada,
- Postal code updates
--- Label should be "Postal code” 
- Hide "Province / State" text box
- Show "Province / Territory"  list
--- Options come from ecer_province (same as used in references)
--- Does NOT include 'Other'
--- Value of list is ecer_abbreviation, Text is ecer_name
------ The user should be able to pick "British Columbia", and then in dynamics it saves the abbreviation BC
--- Default value to British Columbia if no …
> ECER-3095: Accept international addresses and save province name from standard list

- src/ECER.Engines.Validation/Applications/ApplicationRenewalValidationEngine.cs
https://eccbc.atlassian.net/browse/ECER-4373
- Production support issue for applicants applying on the day of expiry. 
- Backend considers someone applying on the day of expiry is Expired. 
- Changed logic to consider today as active. 
User sees this when they try to submit a five year renewal on the day of expiry.
> ecer-4373 renewal error on day of expiry

- src/ECER.Engines.Validation/Applications/RenewalValidationConditions/EceAssistant.cs
- src/ECER.Engines.Validation/Applications/RenewalValidationConditions/FiveYears.cs
- src/ECER.Engines.Validation/Applications/RenewalValidationConditions/OneYear.cs
- src/ECER.Tests/Unit/ApplicationRenewalValidationEngineTests.cs
- updating toast messages when user applies before and after expiry date cutoffs. 
https://eccbc.atlassian.net/browse/ECER-4511 
- etc.
> ecer-4511 update content for toast messags with portal renewal

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue
https://eccbc.atlassian.net/browse/ECER-4513
- allowing dropdowns to show the appropriate value. 
reference is able to submit and the correct province is saved into dynamics.
> fix for province dropdown in references

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
- Added validation
- [ECER-3091](https://eccbc.atlassian.net/browse/ECER-3091)
> ECER-3091: Add validation to education form when application is ECE Assistant + Renewal type

- src/ECER.Resources.Documents/Applications/ApplicationChildren/Transcripts.cs
- Do not set comprehensive report received flag from portal
- [ECER-4365](https://eccbc.atlassian.net/browse/ECER-4365)
> ECER-4365: Do not set comprehensive report received flag from portal (REWORK)

- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationRequirements.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RenewCard.vue
- src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
---
---
Bug was that the user could click into application-requirements when they were trying to learn more during the renewal. 
https://eccbc.atlassian.net/browse/ECER-5081
- Simplified certification-requirements page. Confirmed this was only used for renewal flows before a user is able to renew. Requirements are always the same so we didn't need the additional checks for Labour Mobility + New applications. 
- ECER-{###}
- etc.
> ecer-5081 bug fix simplified learn more renewal flow
