src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package-lock.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Certifications.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ExpandSelect.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/CertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/main.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-checkbox.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-expansion-panel.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-radio.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- Small styling tweaks to select certification type component
- Added missing certification type(s) to swagger/openapi
- Run lint and type-check on `npm run dev`
- Hit BE create draft application endpoint after selecting certification type(s)
=> Connect FE to BE create draft application endpoint

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/client.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/NavigationBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/user.ts
- Logout user when axios 401 error response
- Swap email and phone number order on `/new-user` page (address ECER-595)
- Scroll to top on router change
=> ECER-876: Axios response interceptor for 401 errors

.github/pull_request_template.md, CONTRIBUTING.md
- Branch policy already defined in `CONTRIBUTING.md`
- Added test sections under _Contribute code changes_
- PR template
=> ECER-823: document development process

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/App.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/profile.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationTabs.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ExpandSelect.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Messages.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Profile.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProfileForm.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceAddress.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceAddresses.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/CertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/certification-types.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/profile-information-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/user.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/expand-select.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/input.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/functions.ts
- Addresses component
- Refactored types
- Connected profile endpoints
- [ECER-620](https://eccbc.atlassian.net/browse/ECER-620)
@ytqsl **NOTE** missing corresponding BE fields for FE form fields, specifically:
- Legal Middle Name,
- Preferred Name,
- Previous Name,
- and Alternate Contact Number
I have included all the fields in the form as per the designs.
=> ECER-822: Connect profile endpoints

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/wizard.d.ts
- Adjustments to wizard component and pinia store
- Instantiated wizard component from application page 
- Connected wizard to profile endpoints
- [ECER-713](https://eccbc.atlassian.net/browse/ECER-713)
=> ECER-713: Contact Information step of application wizard

src/.editorconfig, src/Directory.Packages.props, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Program.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.Development.json, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.Test.json, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.json, src/ECER.Utilities.Hosting/ECER.Utilities.Hosting.csproj, src/ECER.Utilities.Hosting/ObservabilityExtensions.cs, src/ECER.Utilities.Hosting/WebApplicationExtensions.cs
ECER-554: security and http improvements
- added middleware to handle security and performance
- ECER-554
=> ECER-554: security and http improvements

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Program.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.json, src/ECER.Utilities.Hosting/WebApplicationExtensions.cs
ECER-554: added disable verbs support and more headers
- added disabled verbes support
- CSP fixes
- ECER-554
=> ECER-554: added disable verbs support and more headers

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/IteRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/SneRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/CertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Requirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts
- Added requirements route
- Content components for different certification type(s)
- [ECER-882](https://eccbc.atlassian.net/browse/ECER-882)
=> ECER-882: Review certification type requirements 

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Login.vue
ECER-{734}: Small change that prevents overlap of the login button. 
- [x ] I have tested these changes locally.
=> quick fix for log in button overlapping on login screen

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/message.ts
- Messages dashboard view UI 
- Message pinia store
- [ECER-779](https://eccbc.atlassian.net/browse/ECER-779)
=> ECER-827: Messages UI

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ExpandSelect.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Form.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProfileForm.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue
small fixes for mobile view for mobile. Also form now validates when they click submit or input information
ECER-734: For a new user - the terms and conditions error message would overlap with the button on mobile view. Adding an extra div removes this overlap. 
Quality of life feature. Clicking the submit button validates the form for missing information. Also adding information into a field validates the field now as well. 
ECER-712: bug fix when choosing certificate type. Wording and mobile view.
=> ECER-734: bug fixes

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Requirements.vue
ECER-882: fix for requirements page. Removed periods from bullet text and added white background.
=> quick fix to remove periods from bullets + add white background to text

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs
This pull request addresses bug fixes and introduces automated tests for application endpoints. Specifically, we have corrected the query bug in the `CommunicationsRepository` file and improved the GET endpoints in the applications module.
Changes Made
1- Bug Fix in Communications Query (CommunicationsRepository File):
Identified and resolved an issue affecting the communications query.
Ensured that the query now functions correctly under all expected conditions.
2- Bug Fix in Applications GET Endpoints:
Addressed a problem in the GET endpoints of the applications module.
Conducted thorough testing to confirm that the endpoints now operate as intended.
3- Automated Tests for Applications GET Endpoint:
added an automated test for the application GET endpoint.
- ECER-1023
- [X ] I have …
=> ECER-1023 application bug fix

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue
ECER-1068: Message Text HTML rendered in FE
In Dynamics, we utilize a rich text editor for composing message bodies. This editor outputs the text in HTML format. Consequently, we render this HTML-formatted text in the frontend.
- ECER-1068
- [ X] I have tested these changes locally.
=> ECER-1068: Message Text HTML rendered in FE

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs
- Update tests for SignedDate field
- Added field to mapper
- [ECER-812](https://eccbc.atlassian.net/browse/ECER-812)
=> ECER-909: Add date field to capture Declaration & Consent signed date

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/EducationCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/EducationList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Form.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/PageContainer.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Snackbar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceAddress.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/education-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/profile-information-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/_colors.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/ecer-theme.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-btn.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/education.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/input.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- Education UI
- [ECER-716](https://eccbc.atlassian.net/browse/ECER-716)
=> ECER-969: Education UI

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Login.vue
ECER-1079: Brief description of the changes
Small change for login page text.
=> fix for login page bc services card

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/apiResultHandler.ts
- Improved API response handling
- Save draft application navigation guard when leaving `/application` route
- [ECER-1003](https://eccbc.atlassian.net/browse/ECER-1003)
=> ECER-1118: Navigation to dashboard

src/Directory.Packages.props, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/ECER.Clients.RegistryPortal.Server.csproj, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Users/UserInfoEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/ecer.clients.registryportal.client.esproj, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs
ECER-1202: Model Validation in Minimal API
- Added API payload validation to automatically return 400 bad requests when payload annotations are not valid.
- updated nuget packages
- ECER-1202
=> ECER-1202: API parameter validations

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/PageContainer.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue
- Style background colour of PageContainer component
- Disable "Save and Continue" button until form is valid
- Add custom validation messages to email and phone fields
- [ECER-1007](https://eccbc.atlassian.net/browse/ECER-1007)
=> ECER-1007: New user error handling

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/character-references-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationMapper.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs
- TBD
- [ECER-1031](https://eccbc.atlassian.net/browse/ECER-933)
- etc.
=> ECER-1031: Character Reference

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationMapper.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs
ECER-1115: Work experience references backend
ECER-1115: work experience references backend
Added backend support for work experience references in the 'Save Draft' feature of the application, along with corresponding tests.
- ECER-1115
- ECER-934
=> ECER-1115: Work experience references backend

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProfileForm.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceAddress.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/profile-information-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/formRules.ts
ECER-1011: Validation error fields for profile
=> adding validation field wording to profile form

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
ECER-1031: BE - FE integration for saving character references.
=> ECER-1031: character references

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/profile-information-form.ts
ECER-1017: Minor change for error validation on profile for alternate phone numbers.
=> minor change for error message for alternate number rules check on input

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WorkExperienceReferenceCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WorkExperienceReferenceProgressBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferencePreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Submitted.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
ECER-1247: Submit application FE piece
- Submit page added to the project
- submit API called in FE
- ECER-1247
=> ECER-1247: Submit application FE piece

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue
- Update toast message copy
- [ECER-947](https://eccbc.atlassian.net/browse/ECER-947)
=> ECER-947: Copy update 

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WorkExperienceReferenceProgressBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Submitted.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Engines.Validation/Applications/ApplicationSubmissionValidationEngine.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/ECER.Tests.csproj, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/RegistryApi/UserInfoTests.cs, src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs, src/ECER.Tests/Unit/ApplicationSubmissionValidationEngineTests.cs
ECER-813: Submit Application
- Validation logic added for application submission
- Application submission endpoint refactored
- Repository edited to handle application submission request
- Submit page added to FE
- Submit API called in FE
- ECER-1248
- ECER-1247
- ECER-1246
- ECER-1353
- ECER-813
=> ECER-813 Submit application

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs, src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs
ECER-1111: Adding delete endpoint in backend
##Description
- Added delete endpoint in backend
- When querying for applications we will never show applications with cancelled status
##Related Jira Issue(s)
ECER-1112
=> ECER-1111 Delete Application backend

src/ECER.Tests/Integration/AuthenticationHelper.cs, src/ECER.Tests/Integration/RegistryApi/UserInfoTests.cs
Fixed missing value when setting the test user claims
=> ECER-1401: integration test fix

src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs
ECER-989: Adding additional validation to the repository layer for submit and cancel. Checking to ensure the status is a draft before submitting or cancelling.
=> ecer-989 adding additional validation to the repository level for submit + cancel applications

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
name: Error handling custom messages
ECER-1019
ECER-1041
- etc.
ECER-1019
ECER-1041
=> ECER-1019: Error handling custom messages

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/PreviewCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationTypePreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReferencePreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceContactInformationPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducationPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferencePreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs
- Modified `PreviewCard` component to reflex validation state
- Adjusted preview section components that use `PreviewCard`
- Fixed broken work experience references validation
- Fixed broken dummy data generator function for Character Reference 
- [ECER-1053](https://eccbc.atlassian.net/browse/ECER-1053)
=> ECER-1053: Preview Page Error Handling

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferencePreview.vue
=> Add last name to work experience references preview

src/ECER.Managers.Registry/CommunicationHandler.cs
=> Adjust unreadMessageCount in communication handler

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts
=> Hide "Save and Continue" and "Save as Draft" when list components are in "add" mode

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProfileForm.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/declaration-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/profile-information-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-text-field.scss
=> Use disable instead of readonly for v-text-field

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/client.ts
=> Reject promise in axios interceptor

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Certifications.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts
=> Expose applications response to template to utilize Suspense

src/ECER.Clients.Api/Program.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/PortalInvitations/PortalInvitationsEndpoints.cs, src/ECER.Managers.Admin/Configurer.cs
=> ECER-1403: Minor fix

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Communications/CommunicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Communications/CommunicationsEndpoints.cs
ECER-{1695}: BE: Modify get messages endpoint data
Modified get messages endpoint to include Message Date (Notified On) and Message Read? (Acknowledged) props
- Parent Story -> ECER-{1250}
=> ECER-1695 -> BE: Modify get messages endpoint data

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Program.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.Development.json, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.Test.json, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/App.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/client.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/NavigationBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProfileForm.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceAddresses.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Login.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/LogoutCallback.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/SigninCallback.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/SilentCallback.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/config.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/oidc.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/user.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/address.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/authority.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/constant.ts
- Cleaned up BE code (removed bcsc and bceid) to just use kc
- Simplified FE pinia store and oidc-client-ts implementation for user storage
- Automatic refresh token flow
- [ECER-1611](https://eccbc.atlassian.net/browse/ECER-1611)
=> ECER-1679: Auth refactor and refresh token flow

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package-lock.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/App.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ConfirmationDialog.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/InactiveSessionTimeout.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/confirmation-dialog.d.ts
- Display inactive session confirmation dialog (modal) when user is inactive for 2 minutes
- 60s countdown to stay logged in
- Refactor confirmation dialog component for 'silent' activator (modal without a button)
- [ECER-1611](https://eccbc.atlassian.net/browse/ECER-1611)
**attn** `npm install` required for new package
=> ECER-1680: Inactive Session Timeout

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Messages.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/PageContainer.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WizardHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/main.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-list-item.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/format.ts
- MessageList and MessageListItem components
- Moved /messages route from dashboard child route to parent
- "Dashboard" changed to "Home" in breadcrumbs
- [ECER-1250](https://eccbc.atlassian.net/browse/ECER-1250)
=> ECER-1692: Message list FE

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Messages.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/PageContainer.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/message.ts, src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs
- FE pagination
- [ECER-1250](https://eccbc.atlassian.net/browse/ECER-1250)
=> ECER-1696: FE pagination

src/ECER.Clients.Api/InviteLinks/InviteLinksEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/reference.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceRadio.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/ReferenceSubmitted.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/work-experience-reference-decline-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/input.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Tests/Integration/RegistryApi/PortalInvitationTests.cs
---
name: Work Experience Reference Opt-out
---
ECER-1226: Work Experience Reference Opt-out
- Work Experience Reference Opt-out implemented in FE project
- ECER-1226
- etc.
=> ECER-1226 Work Experience Reference Opt-out

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/character-reference-decline-form.ts
---
name: Opt-out for character reference
---
ECER-1408: Opt-out for character reference
- opt-out process for character reference added to the project
- etc.
- ECER-1408
=> ECER-1408 Opt out for character reference

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WizardHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationTypePreview.vue
ECER-1674: Changing wording for application header title. 
- Includes minor changes to preview screen. & -> and. 
- Toddle to Toddler
=> bug fix for application header to be dynamic

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Messages.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/message.ts
- Desktop and mobile layout for viewing messages
- Full screen v-dialog on mobile
- Small fix for `/application/undefined`API calls
- [ECER-1256](https://eccbc.atlassian.net/browse/ECER-1256)
=> ECER-1256: READ Message view

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducationPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
---
This fixes some minor FE bugs
---
Warning message shows up for a few seconds after submitting the application
Text mismatch in education and preview pages
Education snack bar should be in success style
- ECER-1868
- ECER-1793
- ECER-1886
=> ECER-1868: Minor FE bug fixes

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDetails.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/character-reference-review-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/work-experience-reference-assessment-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/work-experience-reference-wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/form.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/constant.ts
---
ECER-1269 - WorkEx Reference submission flow - overview and work ex hours details
---
ECER-1269: Work Experience Reference must be able to provide their contact information.
- Work Ex Overview page
- Added work ex hours details section
- ECER-869
- ECER-1269
overview page:
Work Ex hours page:
validations:
=> ECER-1269 - WorkEx Reference submission flow - overview and work ex hours details

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Managers.Registry/ApplicationMapper.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs
---
BE: Create endpoint to get application status
---
This PR Aims at creating an endpoint to get application status
ECER-1834: BE: Create endpoint to get application status
- Created required objects and added required mappings
- Added endpoint, required handlers and repository
- Added automation tests for BE
- ECER-1834
- Parent Story : ECER-1259
=> ECER-1834 - BE: Create endpoint to get application status

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/References/ReferencesEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ReferenceTests.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/Contact.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Application.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Certificate.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_CharacterReference.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Course.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_PostsecondaryInstitute.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Program.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Transcript.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_WorkExperienceRef.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_Investigation.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_InvestigationPlanningInterview.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_PostSecondaryInstituteSiteVisit.cs, src/ECER.Utilities.DataverseSdk/Model/Messages/ecer_ECERCharacterReferenceVerification.cs, src/ECER.Utilities.DataverseSdk/Model/Messages/ecer_ECERWorkExperienceReferenceVerification.cs, src/ECER.Utilities.DataverseSdk/Model/OptionSets/ecer_PSIProgramType.cs, src/ECER.Utilities.DataverseSdk/Model/OptionSets/ecer_ReferenceKnownTime.cs, src/ECER.Utilities.DataverseSdk/Model/ecer.xml
---
ECER-873 - Character/Work Ex reference submission - Updated Dataverse Models, added mappings for length of Acquaintance (Option set) and Will provide reference(bool) prop
---
ECER-873: Character/Work Ex reference submission 
- Updated Dataverse Models
- Added mappings for length of Acquaintance (Option set) and Will provide reference(bool) prop
- ECER-873
- ECER-868
=> Character/Work Ex reference submission - Updated Dataverse Models, added mappings for length of Acquaintance and Will provide reference

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/CheckboxMultiple.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/input.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/formRules.ts
Adding in a common component for multiplecheckbox input component. 
Also removed transition animation between steps in the wizard.
- can we used like this 
=> adding in common multiplecheckbox component

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
- Rework to align with design
- Replace checkboxes with radio buttons for transcript status
- [ECER-716](https://eccbc.atlassian.net/browse/ECER-716)
- [ECER-1333](https://eccbc.atlassian.net/browse/ECER-1333)
=> ECER-716: (rework) use radio buttons for transcript status flags

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue
ECER-{1345}: Print preview for character references page
- Allow user to print what they have submitted 
- Added check to ensure all required fields have been completed before allowing print. 
(If there is a missing element to be completed)
(successful print)
=> reference print their reference on preview page

src/Directory.Packages.props, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue, src/ECER.Managers.Registry/CommunicationHandlers.cs, src/ECER.Managers.Registry/ECER.Managers.Registry.csproj, src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs, src/ECER.Resources.Accounts/ECER.Resources.Accounts.csproj
- Add v-html for displaying rich text
- Sanitize HTML in communication handler
- [ECER-1257](https://eccbc.atlassian.net/browse/ECER-1257)
=> ECER-1257: Portal user can access link in messages

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCertificationTypeHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WizardHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts
ECER-1683: Brief description of the changes
-router addition and also new page for application summary
-included small bug fix for education validation.
/application/summary
wizard
=> mockup for applicaiton summary page completed

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/reference.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContactPreview.vue
Work ex ref submission workflow- Work Experience Reference must be able to submit their completed reference.
---
name: ECER-1273 - Work Experience Reference must be able to submit their completed reference.
about: Work Experience Reference must be able to submit their completed reference.
---
ECER-1273: Work Experience Reference must be able to submit their completed reference.
- FE: Connect FE to BE submit work experience reference endpoint
- Styling corrections for Contact information preview card
- ECER-1273
- ECER-873
- ECER-1883
=> ECER-1273 : FE: Work ex ref submission workflow- Connect FE to BE submit work experience reference endpoint

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/App.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Footer.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Form.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/NavigationBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Profile.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProfileForm.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Login.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/user.ts
- Hide (comment) footer until design is finalized
- Set dashboard width to full container
- Align nav, footer, and body content (consistent margin)
- Use preferred name (if there is one) in authenticated navigation bar
- Regular font weight for navigation bar buttons/links
- Hide application card if application status is not handled
- [ECER-1749](https://eccbc.atlassian.net/browse/ECER-1749)
=> ECER-1749: (REWORK) dashboard and navigation bar

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/App.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/NavigationBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Login.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/SigninCallback.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContactPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceEvaluationPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/oidc.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/format.d.ts
- Remove redirects based on oidc-client-ts events
- Handle redirects in the /signin-callback page
- Pass protected path destination to login page via query params
- Pass protected path destination to oidc-client-ts via `state`
- Date format fix
- Absolute position nav bar
- Adjust nav bar dropdown menu
- [ECER-1682](https://eccbc.atlassian.net/browse/ECER-1682)
=> ECER-1682: Portal will allow links and go to those destinations

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContactPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceAssessment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceEvaluation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceEvaluationPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/ReferencePreviewCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/constant.ts
---
name: Styling fixes for work exp ref submission workflow.
about: Styling fixes for work exp ref submission workflow.
---
Styling fixes for work exp ref submission workflow.
- Styling fixes for work exp ref submission workflow.
- ECER-870
- ECER-869
- ECER-1214
- ECER-1263
=> Styling fixes for work exp ref submission workflow.

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs
---
name: BE: get application status endpoint added will provide reference and adjusted stage statuses
about: BE: get application status endpoint added will provide reference and adjusted stage statuses
---
ECER-1834: BE: get application status endpoint added will provide reference and adjusted stage statuses
-  Added will provide reference prop 
- Adjusted stage statuses to match with dynamics
- ECER-1834
- ECER-1259
=> ECER-1834 - BE: get application status endpoint added will provide reference and adjusted stage statuses

src/ECER.Utilities.DataverseSdk/Model/EcerContext.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/Contact.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Application.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Certificate.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_CertificateType.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_CharacterReference.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Course.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_PreviousAddress.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_PreviousName.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_ProfessionalDevelopment.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Program.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Transcript.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_WorkExperienceAssessment.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_WorkExperienceRef.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_ApplicationAssessment.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_ApplicationAssessmentResult.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_EducationAssessment.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_PSPInterviewQuestion.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_PSPInterviewQuestionTemplate.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_PSPSiteVisitChecklist.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_PSPSiteVisitChecklistTemplate.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_PostSecondaryInstituteCampus.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_PostSecondaryInstituteInterview.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_PostSecondaryInstituteProgramApplicaiton.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_PostSecondaryInstituteSiteVisit.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_ProvincialRequirement.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_RenewalAssessment.cs, src/ECER.Utilities.DataverseSdk/Model/OptionSets/ecer_AssessmentRank.cs, src/ECER.Utilities.DataverseSdk/Model/OptionSets/ecer_PSIDeliveryType.cs, src/ECER.Utilities.DataverseSdk/Model/OptionSets/ecer_PSPIntervieweeType.cs
---
about: Update Dataverse Model from Dynamics
---
Update Dataverse Model from Dynamics
- Update Dataverse Model from Dynamics
=> Update Dataverse Model from Dynamics

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/References/ReferencesEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceAssessment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceAssessmentPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/constant.ts, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ReferenceTests.cs, src/ECER.Utilities.DataverseSdk/Model/OptionSets/ECER_LikeRTScales.cs
---
name: ECER-2004 : Update to Competencies Section of Work Experience Reference Form
about: Update to Competencies Section of Work Experience Reference Form
---
ECER-2004: Update to Competencies Section of Work Experience Reference Form
- Updated Competencies Section of Work Experience Reference Form
- Updated the prop mappings for the Competencies section in the BE
- Updated the Preview page for Competencies section 
- ECER-2004
Competencies section updates:
Preview page changes:
=> ECER-2004 - Update to Competencies Section of Work Experience Reference form

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Submitted.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
ECER-1856: Add route back to manage-application after submission
Changed text for button to Go to application summary
=> changing route to point to manage application after submission

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCertificationTypeHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Banner.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/PreviewCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ResendEmail.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewWorkExperienceReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceRadio.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Login.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/ReferenceSubmitted.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Submitted.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/TermsOfUse.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceEvaluation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceAssessment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceEvaluation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/ReferencePreviewCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/typography.scss
- `ViewWorkExperienceReference` component
- `ViewCharacterReference` component
- Typography heading change
- [ECER-1091](https://eccbc.atlassian.net/browse/ECER-1091)
- [ECER-1092](https://eccbc.atlassian.net/browse/ECER-1092)
=> ECER-2040/2035: View character and work experience reference pages

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/RegistryApi/PortalInvitationTests.cs, src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
ECER-2113: BE work to resent email to reference
- Added two new endpoints to resend invite link to reference
=> Applicant resend link to reference

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/reference.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ResendEmail.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewWorkExperienceReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- Connect FE to BE endpoints
- Loading state for "Resend" button
- Show alert when successfully hit endpoint
- [ECER-1684](https://eccbc.atlassian.net/browse/ECER-1684)
=> ECER-1684: Applicants can resend link to reference

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs
---
ECER-2038 - fixes in application endpoints
---
ECER-2038 - fixes in application endpoints
- fixed openapi operation ID names for endpoints
- minor fix for record summary
- ECER-2038
=> ECER-2038 - fixes in application endpoints

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/reference.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertWorkExperienceReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/character-references-upsert-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/work-experience-reference-upsert-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- `npm run gen-api`
- Call backend endpoints to update character and work experience references 
- [ECER-1092](https://eccbc.atlassian.net/browse/ECER-1092)
- [ECER-1091](https://eccbc.atlassian.net/browse/ECER-1091)
=> ECER-2195: Connect FE to BE for upsert character and work experience references

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts
- Initialize list components in 'list' mode
- Add linting and type-checking to build command 
- [ECER-716](https://eccbc.atlassian.net/browse/ECER-716)
=> ECER-716: Initialize Work Experience Reference(s) and Education(s) components in 'list' mode

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Managers.Registry/PortalInvitationHandlers.cs
- Add error to character reference if matching work experience reference
- Invalidate Portal Invitation if Reference record no longer exists
- [ECER-1041](https://eccbc.atlassian.net/browse/ECER-1041)
=> ECER-1041: Rework error handling

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/RegistryApi/ReferenceTests.cs, src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
---
name: ECER-2228 - BE: Adjust application status endpoint to return all the dynamics status codes
about: Adjust application status endpoint to return all the dynamics status codes
---
ECER-2228 - BE: Adjust application status endpoint to return all the dynamics status codes  (for transcripts, work experience references, and character references)
- BE: Adjusted application status endpoint to return all the dynamics status codes
- Updated automated tests email addresses to unused email domain
- ECER-2228
- ECER-1468
- Updated some email addresses in the automated tests to point to an unused domain on the internet to avoid any accidental email delivery to unintended recipient
=> ECER-2228 - BE: Adjust application status endpoint to return all the dynamics status codes

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCertificationTypeHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryTranscriptReferenceListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ResendEmail.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/typography.scss
- Styling updates from demo feedback
- [ECER-1259](https://eccbc.atlassian.net/browse/ECER-1259)
- [ECER-1091](https://eccbc.atlassian.net/browse/ECER-1091)
- [ECER-1683](https://eccbc.atlassian.net/browse/ECER-1683)
=> ECER-1259 / ECER-1091 / ECER-1683: Styling updates from demo

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCertificationTypeHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryActionListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryCharacterReferenceListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryTranscriptListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryTranscriptReferenceListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ResendEmail.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/typography.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Managers.Registry/PortalInvitationHandlers.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
- Merge master
- npm run gen-api
- Split application summary list items
- [ECER-1468](https://eccbc.atlassian.net/browse/ECER-1468)
=> ECER-2229: Handle changes to application status endpoint

src/Directory.Packages.props, src/ECER.Clients.Api/Program.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Program.cs, src/ECER.Infrastructure.Common/ReflectionExtensions.cs, src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs, src/ECER.Resources.Accounts/Communications/CommunicationRepositoryMapper.cs, src/ECER.Utilities.DataverseSdk/Model/DataverseExtensions.cs
ECER-2239: Brief description of the changes
- nuget package updates
- code warnings fixes
- 
- ECER-2239
=> ECER-2239: 

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationMapper.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Application.cs
---
name: ECER-2208 - BE: Add "request work experience references" flag to application status endpoint
about: BE: Add "request work experience references" flag to application status endpoint
---
ECER-2208 - BE: Add "request work experience references" flag to application status endpoint
- added and mapped ecer_addmorecharacterreference boolean
- added and mapped ecer_addmoreworkexperiencereference boolean
- ECER-2208
- ECER-1850
=> ECER-2208 - BE: Add "request work experience references" flag to application status endpoint

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- Reworked application summary component to leverage vue computed properties
- Type safety from computed properties
-[ECER-1467](https://eccbc.atlassian.net/browse/ECER-1467)
=> ECER-1467: Add new character reference during assessment

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Communications/CommunicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Program.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/appsettings.json, src/ECER.Managers.Registry.Contract/Communications/Contract.cs, src/ECER.Managers.Registry/CommunicationHandlers.cs, src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs, src/ECER.Resources.Accounts/Communications/ICommunicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/CommunicationTests.cs
---
name: Backend Pagination for messages endpoint
---
ECER-1694: Backend pagination added for messages endpoint
- Default values added to the project for pageSize and pageNumber in appsettings.json
- Pagination added to the repository in communication repository
- API endpoint modified to get pageSize and pageNumber from FE in query string
- Automated test modified to cover changed API
- ECER-1694
- etc.
=> ECER-1694: BE pagination for messages endpoint

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryCharacterReferenceListItem.vue
- Fix task colour
- Display character reference(s) that are incomplete
- [ECER-2178](https://eccbc.atlassian.net/browse/ECER-2178)
=> ECER-2178: Show character reference tasks on application summary during assessment

src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs
ECER-1694
- Pagination bug fixed
- ECER-1694
- etc.
=> ECER-1694: pagination bug fixed

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ManageWorkExperienceReferenceListItem.vue
- Rework for text fix
- Adjust text for '-' not '- hours'
- [ECER-2194](https://eccbc.atlassian.net/browse/ECER-2194)
=> ECER-2194: List manage work experience references (REWORK)

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/InactiveSessionTimeout.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertWorkExperienceReference.vue
ECER-2110:  add period to timeout modal 
ECER-1467: removing text add references 
=> quick reworks

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Communications/CommunicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Communications/CommunicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Communications/Contract.cs, src/ECER.Managers.Registry/CommunicationHandlers.cs, src/ECER.Managers.Registry/CommunicationMapper.cs, src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs, src/ECER.Resources.Accounts/Communications/CommunicationRepositoryMapper.cs, src/ECER.Resources.Accounts/Communications/ICommunicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/CommunicationTests.cs
---
name: ECER-2256 - BE: Create endpoint to send messages
about: BE: Create endpoint to send messages
---
ECER-2256 - BE: Create endpoint to send messages
- Added new endpoint for sending messages as portal user (registrant)
- Added handler and repository layer code
- Added/updated prop mappings in all layers
- Added Automated test for sending messages.
- Added Sanitization on the text message coming from the portal user
- ECER-2256
- ECER-1252
=> ECER-2256 - BE: Create endpoint to send messages

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue
- Fix typo
- Handle "Pending" application status
- [ECER-1259](https://eccbc.atlassian.net/browse/ECER-1259)
=> ECER-1259: Handle pending status (REWORK)

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertWorkExperienceReference.vue
- Copy fix
- [ECER-1092](https://eccbc.atlassian.net/browse/ECER-1092)
=> ECER-1092: Copy adjustment (REWORK)

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue
ECER-1791: changing error alert messages
=> rework to change error alert messages

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Certifications/CertificationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Certifications/CertificationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Certifications/Contract.cs, src/ECER.Managers.Registry/CertificationHandlers.cs, src/ECER.Managers.Registry/CertificationMapper.cs, src/ECER.Resources.Documents/Certifications/CertificationRepository.cs, src/ECER.Resources.Documents/Certifications/CertificationRepositoryMapper.cs, src/ECER.Resources.Documents/Certifications/ICertificationRepository.cs, src/ECER.Resources.Documents/Configurer.cs, src/ECER.Tests/Integration/RegistryApi/CertificationTests.cs, src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs, src/ECER.Tests/Integration/Resources/Accounts/Communications/CommunicationRepositoryTests.cs, src/ECER.Tests/Integration/Resources/Certifications/CertificationsRepositoryTests.cs
ECER-2486: BE endpoint for certifications
- Backend endpoint for Certifications added
- Manager layer with mappings created
- Repository layer developed
- Automated tests added
=> ECER 2486: Certification BE piece

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ActionCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RenewCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/certification.ts
- Handles all variations of the renewal card on the dashboard
- [ECER-2405](https://eccbc.atlassian.net/browse/ECER-2405)
- [ECER-2406](https://eccbc.atlassian.net/browse/ECER-2406)
- [ECER-2407](https://eccbc.atlassian.net/browse/ECER-2407)
- [ECER-2408](https://eccbc.atlassian.net/browse/ECER-2408)
- [ECER-2409](https://eccbc.atlassian.net/browse/ECER-2409)
- [ECER-2410](https://eccbc.atlassian.net/browse/ECER-2410)
- [ECER-2407](https://eccbc.atlassian.net/browse/ECER-2411)
=> ECER-2405: Renewal card variations

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs
---
name: ECER-2568: BE: Add required fields to Draft Application endpoint for renewal
about: BE: Add required fields to Draft Application endpoint for renewal
---
ECER-2568: BE: Add required fields to Draft Application endpoint for renewal
- Added and mapped new fields: ecer_type, ecer_educationorigin, ecer_educationrecognition in all the layers
- Exposed new fields: ecer_type, ecer_educationorigin, ecer_educationrecognition in the required application endpoints
- ECER-2568
- ECER-1172
=> ECER-2568: BE: Add required fields to Draft Application endpoint for renewal

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/PreviewCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/wizard.d.ts
- Replace BE PortalStage with FE ApplicationStage
- [ECER-1172](https://eccbc.atlassian.net/browse/ECER-1172)
=> ECER-2578: Create frontend type(s) for PortalStage

src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/Resources/Accounts/Registrants/RegistrantRepositoryTests.cs
---
name: ECER-2570: Add/Adjust automated tests for applications
about: Add/Adjust automated tests for applications
---
ECER-2570: Add/Adjust automated tests for applications
- Added/Adjusted tests for application type(New, Renewal), Education Data, and Application Stage
- Fixed failing Registrant Repository Test due to "Previous Names" changes
- ECER-2570
- ECER-1172
=> ECER-2570: Add/Adjust automated tests for applications

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/EducationList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Wizard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue
ECER-1814: updates to education kust
- updates wording to input fields 
- bug fix that made stepper jump to review when window resized. (using v-show instead of v-if for stepper)
- sentence casing where applicable.
Extra info 
Five Year 
One year 
ECE Assistant 
Headers in add / edit education 
student number or ID 
student name shown on transcript
=> Tasks/ecer 1814 Education updates

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/CertificationType.vue
ECER-1789: Updates to certificate types
Refer to screenshots for content updates 
-Header update to H1
- ECER-1787
=> Certificate updates

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/CertificationTypeRequirements.vue
ECER-1811: Brief description of the changes
- Updates to certificate requirements
- ECER-1787
=> certificate requirement updates

src/ECER.Clients.Api/appsettings.json
ECER-n/a: fix to correct test and local deployments from failing. 
=> quick fix for missing file config

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WizardHeader.vue
ECER-1785: Feedback from QA
- text change
=> quick fix text change changing certificate type

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue
ECER-1801: QA feedback text change for back button on mobile.
=> QA feedback. Back button to link at top of page for mobile

src/ECER.Clients.Api/Files/FileEndpoints.cs, src/ECER.Tests/Integration/Api/FileTests.cs
fixes API upload file endpoint return issue
=> this fixes file endpoint return result issue

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
- Styling
- [ECER-1337](https://eccbc.atlassian.net/browse/ECER-1337)
=> ECER-1337: Remove bold (REWORK)

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/AuthenticationService.cs, src/ECER.Infrastructure.Common/DistributedCacheExtensions.cs
ECER-1243: Fix for 403 issues due to caching null values
=> ECER-1243: fix for caching null values

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/main.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-stepper.scss
ECER-1795: stepper changes from rework ticket
=> styling stepper to match figma rework

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCertificationTypeHeader.vue
- Adjust copy
- [ECER-2358](https://eccbc.atlassian.net/browse/ECER-2358)
=> ECER-2358: Update page title on application summary for renewal applications

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/_colors.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/ecer-theme.ts
---
name: ECER-2199: Styling fixes
---
ECER-2199: Styling fixes
- Fixed v-divider color for messages
- adjusted v-divider spacing for view messages
- ECER-2199
=> ECER-2199: Styling fixes

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WizardHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-stepper.scss
ECER-1795: changed position of save and exit button on mobile. changed color for current step in the stepper. 
- ECER-1801
- etc.
=> rework stepper current step color and moving save and exit button

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProfileForm.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/EditProfile.vue
- Add old profile form to edit-profile page to unblock portal
- [ECER-1771](https://eccbc.atlassian.net/browse/ECER-1771)
=> Add existing (old) profile form to edit-profile page

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs
quick fix bad formatted date for created on field in FE
=> quick fix bad formatted date for created on field in FE

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Files/FilesEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/message.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/DownloadFileLink.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- Communication files loaded in the Front-end messages page
- General component to load uploaded files
- Backend endpoint to return files for communications
- ECER-2461
- ECER-2189
=> Tasks/ecer 2461: FE piece for communication files

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RenewCard.vue
ECER-2726: styling fix for renew cards to look like links. 
=> bug fix link style renew card

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/VerifyPreviousName.vue
ECER-2470: Upload ID for previous name -> FE: Implement file upload page
- FE: Implement file upload page
- ECER-2470
- ECER-2245
clicking on "Send" without adding any file:
valid file attached:
Invalid file attached and clicking on "Send":
=> ECER-2470: Upload ID for previous name -> FE: Implement file upload page

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Files/FilesEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ReplyToMessage.vue, src/ECER.Managers.Registry/CommunicationMapper.cs, src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs, src/ECER.Resources.Accounts/Communications/ICommunicationRepository.cs, src/ECER.Resources.Accounts/ECER.Resources.Accounts.csproj, src/ECER.Resources.Documents/Applications/ApplicationChildren/ProfessionalDevelopments.cs
ECER-1253: File Upload for communications
- Cover file upload backend and frontend for communications
- ECER-1253
- etc.
=> stories/ecer-1253: File Upload for communications

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRenewalRequirements.vue
- Add missing text to One Year renewal requirements
- [ECER-1173](https://eccbc.atlassian.net/browse/ECER-1173)
=> ECER-1173: Add missing text block to ECEOneYearRenewalRequirements (REWORK)

src/ECER.Engines.Validation/Applications/RenewalValidationConditions/EceAssistant.cs, src/ECER.Engines.Validation/Applications/RenewalValidationConditions/FiveYears.cs, src/ECER.Engines.Validation/Applications/RenewalValidationConditions/OneYear.cs, src/ECER.Tests/Unit/ApplicationRenewalValidationEngineTests.cs
All the validation engine rules for renewal flow + related unit tests
- Validation rules in Backend validation engine added
- Related unit tests added
ECER-2752
ECER-2793
ECER-2797
ECER-2803
ECER-2800
=> Validation engine rules for renewal flow

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Declaration.vue
- Added loading state to button
- [ECER-3019](https://eccbc.atlassian.net/browse/ECER-3019)
=> ECER-3019: Add loading state to continue button for declaration and consent section of application wizard

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ManageWorkExperienceReferenceList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertWorkExperienceReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewWorkExperienceReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferencePreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-assistant-and-one-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-five-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-assistant.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-five-year-active.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-five-year-expired-less-than-five-years.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-five-year-expired-more-than-five-years.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-one-year-active.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-one-year-expired.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/references-form.ts
- Copy changes
- [ECER-2932](https://eccbc.atlassian.net/browse/ECER-2932)
=> ECER-2932: Wording mismatch in stepper

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Files/FilesEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/.vscode/extensions.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/client.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/FileUploader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/apiResultHandler.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/functions.ts
- Remove vetur from extension recommendations
- Fix error handling to ensure we are rejecting promise
- Sanitize filename BE+FE
- [ECER-3013](https://eccbc.atlassian.net/browse/ECER-3013)
=> ECER-3013: File upload failing in client for some files

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RenewCard.vue
- Adjust renew card text 
- Adjust canRenew logic
- [ECER-1175](https://eccbc.atlassian.net/browse/ECER-1175)
=> ECER-1175: Renewal instructions for ECE Five Year certifications + specializations

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/SigninCallback.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/oidc.ts
ECER-1165: Account setup page to collect ECE number
- ECER-1165
=> ECER-1165: account setup page to collect ECE number

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-assistant-review-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-assistant.ts
ECER-1822: Application form wizard for renewing ECE Assistant
- Application form wizard for renewing ECE Assistant
- ECER-1822
- ECER-2753
=> ECER-1822: Application form wizard for renewing ECE Assistant

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ManageWorkExperienceReferenceList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/UpsertWorkExperienceReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Resources.Documents/Applications/ApplicationChildren/WorkExperienceReferences.cs
ECER-1077: Application Summary tasks for 400 hour work experience
- Added/adjusted application Summary tasks for 400 hour work experience
- Added/adjusted manage 400 hour work experience references
- ECER-1077
- ECER-2352
=> ECER-1077: Application Summary tasks for 400 hour work experience

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/EducationList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-assistant-review-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-renew-assistant.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts
ECER-1185: Updating education pieces 
- Changed add education to sentence casing 
- used draftApplicationFlow to determine what we display for the education pieces
- also has the designs for the ITE + SNE flows 
- updated error validation messaging
- added in review screen for eceAssistant renewal. 
Assistant renewal flow
Review screen 
=> fixing education display text and adding in draftApplicationFlow

src/ECER.Resources.Accounts/Registrants/RegistrantRepository.cs
---
---
- etc.
- ECER-{###}
- etc.
=> fixing isverified bug from being overwritten

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
- Hide options if we have an in progress application
- [ECER-2842](https://eccbc.atlassian.net/browse/ECER-2842)
=> ECER-2842: Dashboard updates to handle renewal flow

src/ECER.Managers.Registry/RegistrantHandlers.cs, src/ECER.Managers.Registry/RegistrantMapper.cs, src/ECER.Resources.Accounts/Registrants/RegistrantRepository.cs
=> fix portal authentication

src/ECER.Resources.Accounts/Registrants/RegistrantRepository.cs
=> patch for input exception

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/user.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProfileForm.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue
ECER-1918: submitted previous name in application summary page problem fixed
ECER-3170: Loading progressbar for new-user page submit action added when they login for first time
=> Fix/ecer 3170:

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Users/UserInfoEndpoints.cs, src/ECER.Managers.Registry/RegistrantMapper.cs
fix for middle name mapping for new portal user
- fix for middle name mapping for new portal user
- ECER-1166
=> fix for middle name mapping for new portal user

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/App.vue
- Hide navigation bar and footer when router path includes "reply"
- [ECER-3119](https://eccbc.atlassian.net/browse/ECER-3119)
=> ECER-3119: Hide navigation bar and footer when replying to messages

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ConfirmationDialog.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue
- Adjust margin
- [ECER-3102](https://eccbc.atlassian.net/browse/ECER-3102)
=> ECER-3102: Adjust icon margin

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ConfirmationDialog.vue
- Wrap title text of confirmation dialog
- [ECER-3034](https://eccbc.atlassian.net/browse/ECER-3034)
=> ECER-3034: Fix confirmation dialog title text

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Resources.Documents/Applications/ApplicationChildren/ProfessionalDevelopments.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs
ECER-2848: BE: Create endpoint to add professional development to an existing application
- BE: Create endpoint to add professional development to an existing application
- BE: Add automation tests for the new create endpoint to add professional development
- new endpoint / manager to add professional development to an existing application
- Leveraging existing functions in applicationChildren to modify the files.
- ECER-2354
- ECER-2848
- ECER-2851
=> ECER-2848: BE: Create endpoint to add professional development to an existing application

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/README.md
=> adding local clam av setup into readme

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/EducationList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-assistant-and-one-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/review-submit-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/_colors.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-stepper.scss
ECER-3118
- sentence casing 
- stepper text colors
- space between lines
- focus goes back up after cancel and adding
- text wrap for intro sentences
=> minor fixes to education and stepper colors

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
ECER-3271: end date for education not validating 
ECER-3272: Edit icon not working when resaving education
=> fixing education bugs

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue
ECER-3294: bug fix date format in work experience.
=> bug fix for date format

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Certifications/CertificationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Certifications/CertificationsEndpoints.cs, src/ECER.Managers.Registry.Contract/Certifications/Contract.cs, src/ECER.Managers.Registry/CertificationHandlers.cs, src/ECER.Managers.Registry/CertificationMapper.cs, src/ECER.Resources.Documents/Certifications/CertificationRepository.cs, src/ECER.Resources.Documents/Certifications/CertificationRepositoryMapper.cs, src/ECER.Resources.Documents/Certifications/ICertificationRepository.cs, src/ECER.Tests/Integration/RegistryApi/CertificationTests.cs, src/ECER.Tests/Integration/RegistryPortalWebAppScenarioBase.cs, src/ECER.Tests/Integration/Utilities/DataverseSdk/QueryTests.cs, src/ECER.Utilities.DataverseSdk/Queries/Join2QueryExpressionBuilder.cs
ECER-3208: Create public lookup page with search fields
- BE: Create certification record query
- BE: Add automated tests
- Nested Object Join fixed in Query expression builder
- Mapped certificate conditions from nested ecer_certificateconditions Entity (From Contact Entity), Fixed Automated tests
- ECER-3208
- ECER-3223
- ECER-3226
=> ECER-3208: Create public lookup page with search fields - BE Pieces

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package-lock.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/App.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Declaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Footer.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ManageProfessionalDevelopmentList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ManageWorkExperienceReferenceList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/NavigationBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RegistrantCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RenewCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WizardHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/LogoutCallback.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/PageNotFound.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/SigninCallback.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/TermsOfUse.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/main.ts
- Delay calling `app.use(router)` until after the oidc configuration has been fetched, instantiating the router was causing a `getUser()` call that was creating the oidc-client-ts `UserManager` without the required configuration
- NPM package updates
- [ECER-3262](https://eccbc.atlassian.net/browse/ECER-3262)
=> ECER-3262: Portal Log In Button Not Redirecting to BCSC

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEIteRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECESneRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/FileUploader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ReplyToMessage.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceFiveYearRenewalExplanationPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceOneYearRenewalExplanationPreview.vue
- Reworks
- [ECER-3119](https://eccbc.atlassian.net/browse/ECER-3119)
- [ECER-3211](https://eccbc.atlassian.net/browse/ECER-3211)
- [ECER-1839](https://eccbc.atlassian.net/browse/ECER-1839)
=> Bug fixes for ECER-3119/3211/1839

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Declaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue
- Router fix
- Wizard fix
- [ECER-3371](https://eccbc.atlassian.net/browse/ECER-3371)
=> ECER-3371: Summary screen missing shows work experience instead on new 1 year application

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
ECER-1794: Focus not being set to top of page
- ECER-1794: Fix for - Focus not being set to top of page
- ECER-1794
=> ECER-1794: Focus not being set to top of page

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/App.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/message.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/profile.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/user.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Loading.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Messages.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Profile.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RegistrantCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/config.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/oidc.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/main.scss, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/tsconfig.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/tsconfig.node.json
ECER-3397: Spinner implemented in the dashboard and messages pages
ECER-3397: HTTP Calls moved to mounted async function in profile page and dashboard
=> Fix/ecer 3397: Performance enhancements

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/user.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-labor-mobility-assistant-and-one-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/application-wizard-labor-mobility-five-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/preview-form-labor-mobility-assistant-and-one-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/preview-form-labor-mobility-five-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts
- Radio buttons for labor mobility selection 
- Hide education section
- Show certification information section
- Application configurations to hide education step on wizard and review
- [ECER-3408](https://eccbc.atlassian.net/browse/ECER-3408)
- [ECER-3409](https://eccbc.atlassian.net/browse/ECER-3409)
- [ECER-3410](https://eccbc.atlassian.net/browse/ECER-3410)
=> ECER-3430: FE Labor Mobility

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/EducationList.vue
ECER-1731: Quick text fix 
- ECER-{###}
- etc.
=> text changes for education list

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/profile.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/user.ts
- Suppress error toast
- Block on get profile call
- [ECER-3458](https://eccbc.atlassian.net/browse/ECER-3458)
=> ECER-3458: Fix for new user flow

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/profile.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Login.vue
- New layout
- Remove BCeID option
- [ECER-3275](https://eccbc.atlassian.net/browse/ECER-3275)
=> ECER-3275: Update portal landing page to remove BCeID and update BCSC content

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-stepper.scss
ECER-3268: changing opacity on -v-stepper-item
Before
After
=> changing opacity on v-stepper

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/LookupCertificationRecord.vue
ECER-3210:: Minor text update 
- Update "Certificate Terms and Conditions" to  "Certificate terms and conditions"
- ECER-3210
=> ECER-3210: Update LookupCertificationRecord.vue

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package-lock.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json
ECER-3521: https://eccbc.atlassian.net/browse/ECER-3521
- updating dependencies.
=> dependabot updates ECER-3521

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts
- Fix broken ID reference
- [ECER-3511](https://eccbc.atlassian.net/browse/ECER-3511)
=> ECER-3511/3526: Fix ID to include WE references in application payload

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Submitted.vue
- Adjust logic to use string type
- [ECER-2945](https://eccbc.atlassian.net/browse/ECER-2945)
=> ECER-2945: Patch for draftApplicationHasEducationNotRecognized logic

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDeclaration.vue
ECER-3368: line spacing updates to match figma 
https://eccbc.atlassian.net/browse/ECER-3368 
- added blue banner background
- Bolded user name
- Unbolded certificate type
- added additional spacing between bullet points
- reduced spacing from continue button
=> bug fix to match figma ecer-3368

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/EducationList.vue
- added education training program where necessary
- education list details to show when upgrading
- ECER-1743 https://eccbc.atlassian.net/browse/ECER-1743
- ECER-1731 https://eccbc.atlassian.net/browse/ECER-1731
Registrant flow with Five Year
=> fixing text and flows for five year registrants

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/AddProfessionalDevelopment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/FileUploader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceProfessionalDevelopment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs
Bug fixes and enhancements
- ECER-3413: End date is throwing error message when user selects start date from the date picker
- ECER-3008: Certificate status text got chopped off in mobile breakpoint
- ECER-3528: TECH: Adjustments to support manual application type
- ECER-3413
- ECER-3008
- ECER-3528
ECER-3008: Certification status chips in mobile view:
=> Bug fixes and enhancements

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/v-btn.scss
ecer-3297: https://eccbc.atlassian.net/browse/ECER-3297
- Adjusted line spacing global change
Before
After
Before
After
=> letter spacing for all buttons

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Footer.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/LookupCertification.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCheckbox.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceRecaptcha.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceEvaluation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContactPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReference400HoursEvaluation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceAssessmentPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceEvaluation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceEvaluationPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/format.d.ts
- Fix recaptcha
- Add label to v-auto-complete
- Broken EceDateInputs in references
- [ECER-2891](https://eccbc.atlassian.net/browse/ECER-2891)
=> ECER-2891: Retouches for issues found in dev env

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Declaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRenewalRequirements.vue
- Copy change
- Fix declaration `EceCheckbox`
- [ECER-1173](https://eccbc.atlassian.net/browse/ECER-1173)
- [ECER-2891](https://eccbc.atlassian.net/browse/ECER-2891)
=> ECER-1173: REWORK copy change and checkbox fix

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Declaration.vue
- Rework copy change
- [ECER-2891](https://eccbc.atlassian.net/browse/ECER-2891)
=> ECER-2891: REWORK copy change

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
- [ECER-3356](https://eccbc.atlassian.net/browse/ECER-3356)
=> ECER-3356: Open terms of use in new tab from new user page

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Submitted.vue
- [ECER-3556](https://eccbc.atlassian.net/browse/ECER-3556)
=> ECER-3556: Copy change

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package-lock.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json
- Updates packages to flagged by dependabot. 
=> update dependabot npm dependencies

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/AddProfessionalDevelopment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/FileUploader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceProfessionalDevelopment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferencePreview.vue
- Fix website URL field in Professional Development entry
- Add max files prop in `EceProfessionalDevelopment` -> `FileUploader` component
- [ECER-3637](https://eccbc.atlassian.net/browse/ECER-3637)
=> ECER-3637: Fix website URL field in Professional Development

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationRequirements.vue
ECER-3557: https://eccbc.atlassian.net/browse/ECER-3557 content update
- showing all instructions when one year certificate is expired.
- ECER-{###}
- etc.
=> adding instructions for expired one year renewal requirements

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs
- Order applications by createdOn date desc
- Disregard "Complete" and "Decision" applications on portal
- [ECER-3640](https://eccbc.atlassian.net/browse/ECER-3640)
=> ECER-3640: Adjust latest application logic

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRenewalRequirements.vue
- Content updates to 5 year renewal requirements
- [ECER-1175](https://eccbc.atlassian.net/browse/ECER-1175)
=> ECER-1175: Content updates

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCertificationTypeHeader.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRenewalRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRenewalRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEIteRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRenewalRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECESneRegistrantRequirements.vue
- Changes for ECER-3587/3584/3585/3620
- [ECER-3587](https://eccbc.atlassian.net/browse/ECER-3587)
- [ECER-3584](https://eccbc.atlassian.net/browse/ECER-3584)
- [ECER-3585](https://eccbc.atlassian.net/browse/ECER-3585)
- [ECER-3620](https://eccbc.atlassian.net/browse/ECER-3620)
=> ECER-3579: High priority content updates

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/application.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Resources.Documents/Applications/ApplicationChildren/ProfessionalDevelopments.cs, src/ECER.Resources.Documents/Applications/ApplicationRepository.cs, src/ECER.Tests/Integration/RegistryApi/ApplicationTests.cs, src/ECER.Tests/Integration/Utilities/DataverseSdk/QueryTests.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_Certificate.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_EducationAssessment.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ecer_Investigation.cs, src/ECER.Utilities.DataverseSdk/Queries/Join2QueryExpressionBuilder.cs
ECER-3637, ECER-3792, ECER-3793: Addressing Issues with Professional Development Upload, Query Expression Builder, and Application Object Response
This pull request addresses multiple issues reported in the system, as described below:
Ensured proper mapping and validation of uploaded files to reflect accurately in the CMS.
Resolved a bug in the query expression builder that caused nested entities to fail during loading.
Updated the backend to return fresh application objects, including all updated IDs, in the response of the PUT application endpoint.
This change ensures proper synchronization with the front-end, allowing subsequent save calls to include all necessary IDs to prevent the creation of unnecessary records in Dynamics.
- ECER-3637
- ECER-3792
- ECER-3793
Include screenshots to …
=> ECER-3637, ECER-3792, ECER-3793: Query expression builder, Application Object Response

src/ECER.Tests/Integration/Utilities/DataverseSdk/QueryTests.cs, src/ECER.Utilities.DataverseSdk/Queries/Join2QueryExpressionBuilder.cs
=> ECER-3637: entities problem fixed

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue
- Copy change
- [ECER-3585](https://eccbc.atlassian.net/browse/ECER-3585)
=> ECER-3585: Add "Is not the same person as your character reference"

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRenewalRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue
- Copy change
- [ECER-1173](https://eccbc.atlassian.net/browse/ECER-1173)
=> ECER-1173: Copy change (REWORK)

src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs
- etc.
- [ECER-3672](https://eccbc.atlassian.net/browse/ECER-3672)
=> ECEC=3672: Adjust ecer_DocumentInternallyReviewed field constant

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceOneYearRenewalInformation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/constant.ts, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Unit/ApplicationRenewalValidationEngineTests.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_WorkExperienceAssessment.cs, src/ECER.Utilities.DataverseSdk/Model/Entities/ECER_WorkExperienceRef.cs, src/ECER.Utilities.DataverseSdk/Model/OptionSets/ecer_fiveyrrenewalexplanations.cs, src/ECER.Utilities.DataverseSdk/Model/OptionSets/ecer_yrrenewalexplanations.cs
- Correct reversed renewal explanation reasons
- [ECER-2996](https://eccbc.atlassian.net/browse/ECER-2996)
=> ECER-2996: Swap renewal reasons [REWORK]

src/ECER.Resources.Documents/Applications/ApplicationChildren/CharacterReferences.cs, src/ECER.Resources.Documents/Applications/ApplicationChildren/ProfessionalDevelopments.cs, src/ECER.Resources.Documents/Applications/ApplicationChildren/Transcripts.cs, src/ECER.Resources.Documents/Applications/ApplicationChildren/WorkExperienceReferences.cs
- [ECER-3813](https://eccbc.atlassian.net/browse/ECER-3813)
=> ECER-3813: Fix null StatusCode's in application child entities

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRenewalRequirements.vue
- Text change
- [ECER-3585](https://eccbc.atlassian.net/browse/ECER-3585)
=> ECER-3585: Requirements copy [REWORK]

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue
- Add status for previous name to application summary
- [ECER-1918](https://eccbc.atlassian.net/browse/ECER-1918)
=> ECER-1918: Updates to previous name tasks on application summary

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/NavigationBar.vue
ECER-3859: Portal link temporarily deactivated
- ECER-3859
- etc.
=> ECER-3859: router link temporarily deactivated in front-end

src/ECER.Utilities.DataverseSdk/Queries/Join2QueryExpressionBuilder.cs
problem with empty key fixed in nested object loader
- ECER-3915
- etc.
=> ECER-3915: Nested objects empty key problem fixed

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceTextField.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue
https://eccbc.atlassian.net/browse/ECER-3990 
- User unable to select province dropdown 
=> bug fix, province drop down doesn't work for work experience reference

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/DownloadFileLink.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-3675: download file safari problem fixed

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue
---
---
https://eccbc.atlassian.net/browse/ECER-3887 
- Cause was when users are logging in they go to the dashboard page ("/") router which checks whether they are logged in, while also firing off calls to grab their applications etc. before redirecting them to the login page
- Fix was to interrupt the application from making the api calls that require authorization and direct the user to the login page
- also added a loading spinner in the new-user page for the cancel button. 
=> reducing 401 calls

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/DownloadFileLink.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Message.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-3675: download file if is safari

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue
ECER-3917: Block users while they are waiting to be redirected to the dashboard
- etc.
=> ECER-3917: Block user while new user save

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
https://eccbc.atlassian.net/browse/ECER-4000 
=> changing label for education

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-4020: update model value after selection

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-4020: remove update datepicker value

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-4020: type property removed

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceReferenceContact.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-2040: V-model replaced

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Profile.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/AddPreviousName.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/VerifyPreviousName.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-3583: Name change document changes

src/Directory.Packages.props, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package-lock.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json
---
---
- etc.
- ECER-{###}
- etc.
=> Update Nuget and NPM packages

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceDateInput.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-3892: Dateinput Required problem fixed

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/LookupCertification.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-4200: Fixed required padding

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Login.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Register.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
- Refactor login page as per Figma designs
- [ECER-2856](https://eccbc.atlassian.net/browse/ECER-2856)
=> ECER-2856: Landing page redesign

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package-lock.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json
---
---
- etc.
- ECER-{###}
- etc.
=> upgrade packages

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Certifications/CertificationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/certification.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/file.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Managers.Registry.Contract/Certifications/Contract.cs, src/ECER.Managers.Registry/CertificationHandlers.cs, src/ECER.Resources.Documents/Certifications/CertificationRepository.cs, src/ECER.Resources.Documents/Certifications/CertificationRepositoryMapper.cs, src/ECER.Resources.Documents/Certifications/ICertificationRepository.cs, src/ECER.Tests/Integration/RegistryApi/CertificationTests.cs
ECER-3818: Brief description of the changes
- Certificate generation API Endpoint added to Certification Endpoints
- Front-end Call to generate the certificate and handle user interface
- ECER-3818
- etc.
=> Stories/ecer 3818: Automatic Certificate Pdf generation for not generated ones

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/oidc.ts
- Add Basic BCeID flow to new user page
- [ECER-2855](https://eccbc.atlassian.net/browse/ECER-2855)
=> ECER-2855: Add Basic BCeID flow to new user page

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/AddProfessionalDevelopment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ProgressBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceProfessionalDevelopment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/formRules.ts, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs
https://eccbc.atlassian.net/browse/ECER-4234 
- Allow professional development to accept decimal places
- set backend fields to decimal instead of int. 
- needed to remove number keypress restriction
=> ecer-4234 allowing professional development to accept decimal numbers

src/ECER.Resources.Accounts/Registrants/RegistrantRepository.cs
---
---
- etc.
- ECER-{###}
- etc.
=> Has provided Id flag set for contact bceid verification

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package-lock.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json
Updating dependabot
- tested locally saving a renewal application
- pinia update to v3 doesn't have breaking changes so no concerns here https://pinia.vuejs.org/cookbook/migration-v2-v3.html
=> update dependencies portal

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEIteRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECESneRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/styles/typography.scss
https://eccbc.atlassian.net/browse/ECER-4354
- requirements text content update
=> ecer-4354 content update for requirements

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/AuthenticationService.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Tests/Integration/AuthenticationHelper.cs
- Expand policy to allow for document upload when `PendingForDocuments`
- Adjust dashboard to handle `PendingForDocuments`
- [ECER-2861](https://eccbc.atlassian.net/browse/ECER-2861)
=> ECER-2861: Handle rejected ID flow

src/ECER.Engines.Validation/Applications/ApplicationRenewalValidationEngine.cs
fixing renewal when applying on the expiry date
https://eccbc.atlassian.net/browse/ECER-4373
=> ecer-4373 renewal error on day of expiry

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Submitted.vue
rework 
https://eccbc.atlassian.net/browse/ECER-4357 
- bolding additional text
=> adding bolded text to submitted screen

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
https://eccbc.atlassian.net/browse/ECER-2941
- saving fields based on user inputs.
=> setting educationRecognition and origin fields

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress.config.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/auth.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/newCertifications/newECEAssistantCertification.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/support/selectors.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Declaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificationTypePreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCharacterReferencePreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducationPreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Application.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Submitted.vue
ECER-4261: Automation_Certification ECEA_E2E
- Added ne Cypress E2E Automation test for New ECE Assistant Certification
- Added selectors in cypress to grab required page element for interaction
- Updated all required component's elements to include id tag
- Updated config to run tests for Desktop viewport ONLY for now, can be changed later if needed
- ECER-4261
- ECER-4253
=> ECER-4261: Automation_Certification ECEA_E2E

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/newCertifications/newECE5YearCertification.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/support/selectors.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferencePreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceWorkExperienceReferences.vue
ECER-4262: Automation_Certification creation for ECE 5 year in portal
- Added automation tests for ECE 5 Year Certification New application
- Added selectors for work exp. reference 
- Added element IDs for work exp. reference
- ECER-4262
- ECER-4253
=> ECER-4262: Automation_Certification creation for ECE 5 year in portal

.github/workflows/regression-test.yml
https://eccbc.atlassian.net/browse/ECER-4552 
- github action to run cypress test. 
- TODO: set up github actions secrets for the DEV environment.
=> trying out cypress github action

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/newCertifications/newECEOneYearCertification.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/support/selectors.ts
ECER-4203: Automation_Certification creation for ECE 1 year in portal
- Added Automation tests for New ECE 1 Year Certification application
- Updated selectors
- ECER-4203
- ECER-4253
=> ECER-4203: Automation_Certification creation for ECE 1 year in portal

src/ECER.Resources.Documents/Applications/ApplicationChildren/Transcripts.cs
---
---
- etc.
- ECER-{###}
- etc.
=> comprehensive flag bug fixed

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue
ECER-2852: When message page is loading, no message is displayed. It should show the first item on the list
- etc.
- ECER-{###}
- etc.
=> ECER-2852: First message loaded on message list fetch

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducationPreview.vue
- QA feedback fixes for ECER-1737 and ECER-4356
- [ECER-1737](https://eccbc.atlassian.net/browse/ECER-1737)
- [ECER-4356](https://eccbc.atlassian.net/browse/ECER-4356)
=> ECER-1737: QA feedback on equivalency application stories

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/SpecializedCertificationOptions.vue
https://eccbc.atlassian.net/browse/ECER-4282 
- Update content
- Updated new 5 year education requirements for ITE + SNE 
- Updated 5 year registrant flow education requirement and for the specialized flows
- Other requirement screens already had the content 
=> ecer-4282 content update education requirements

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryActionListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryCharacterReferenceListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryTranscriptListItem.vue
- Change action item text from "Complete"/"Incomplete" to "Received"/"Not yet received"
- [ECER-4483](https://eccbc.atlassian.net/browse/ECER-4483)
=> ECER-4483: Missed copy change for status text

src/Directory.Packages.props, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package-lock.json, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/package.json
---
---
- etc.
- ECER-{###}
- etc.
=> dependency upgrade

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewCourseOutline.vue
no ticket
figma https://www.figma.com/design/f3cLsDnySbxAapZN4RzV7W/ECC-Design-Library?node-id=24407-235124&t=qbU2EKuLHTHbIoDl-0 
- breadcrumb fix
- ECER-{###}
- etc.
=> quick fix for breadcrumb to match figma

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue
ECER-3124: No messages text added to `/messages` page
- etc.
- ECER-{###}
- etc.
=> ECER-3124: Show no messages text

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/VerifyIdentification.vue
Rework ticket to change successful snackbar
---
---
https://eccbc.atlassian.net/browse/ECER-2861
- etc.
- ECER-{###}
- etc.
=> updated snackbard text

.github/workflows/api-build.yml, .github/workflows/e2eTestData-api-build.yml, src/e2eTestData.Dockerfile, tools/helm/tools/values.yaml
WIP to build e2eTestData api to be put / referenced in openshift. 
https://eccbc.atlassian.net/browse/ECER-4557 
- etc.
- ECER-{###}
- etc.
=> ecer-4557 WIP loading in docker build changes for the new API

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
---
---
https://eccbc.atlassian.net/browse/ECER-4605?linkSource=email
- etc.
- ECER-{###}
- etc.
=> ecer-4605 rework adding periods at the ends of the options

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewTranscriptDetails.vue
---
---
- etc.
- ECER-{###}
- etc.
=> demo feedback typo

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-4674: Messages issue in demo fixed

src/ECER.Clients.E2ETestData/Program.cs
---
---
- etc.
- ECER-{###}
- etc.
=> adding in health checks so it runs on openshfit

.github/workflows/tag-create.git.and.imagestream.tag.yaml, CONTRIBUTING.md
---
---
new action to git tag from master or release/master branch and also tag images in openshift. 
- ECER-{###}
- etc.
=> adding in git tag + tag in openshift capability

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ViewProgramConfirmationForm.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
- Adjust validation message copy
- [ECER-1739](https://eccbc.atlassian.net/browse/ECER-1739)
=> ECER-1739: Rework copy

.github/workflows/tag-create.git.and.imagestream.tag.yaml
---
---
- etc.
- ECER-{###}
- etc.
=> quick fix to show what the modified branch name is

.github/workflows/tag-create.git.and.imagestream.tag.yaml
---
---
- etc.
- ECER-{###}
- etc.
=> removing e2etestapi tagging since this doesn't exist in release/master

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageList.vue
fixes issue where having only 1 message shows nothing. 
- etc.
- ECER-{###}
- etc.
=> adding in message fix for just having 1 message

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEducation.vue
- Content updates
- [ECER-1739](https://eccbc.atlassian.net/browse/ECER-1739)
=> ECER-1739: Update content

.github/workflows/build-template.yml, .github/workflows/tag-create.git.and.imagestream.tag.yaml
this is creating a create tag function for our repository to help us version our deployments. 
running the action will : 
- verify that we running the action in the correct branch with a valid version
- build new images for our 3 applications 
- tag the images in openshift 
- tag the code in github 
- etc.
- ECER-{###}
- etc.
=> implementing create tag

.github/workflows/build-template.yml, .github/workflows/tag-create.git.and.imagestream.tag.yaml
---
---
- etc.
- ECER-{###}
- etc.
=> adding tagging to release branch without e2eTestData

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/AddProfessionalDevelopment.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RenewCard.vue
ECER-4746: Add "id" locators to professional development form  for renewal flow
- Add "id" locators to professional development form  for renewal flow
- ECER-4746
- ECER-4253
=> ECER-4746: Add "id" locators to professional development form  for renewal flow

.github/workflows/deploy-to-prod.yaml
---
---
- etc.
- ECER-{###}
- etc.
=> allowing us to deploy from UAT to production

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceProfessionalDevelopment.vue
ECER-4746: Add ID locators to Professional Dev page - Renewal workflow
- ECER-4746: Add ID locators to Professional Dev page - Renewal workflow
- ECER-4746
- ECER-4253
=> ECER-4746: Add ID locators to Professional Dev page - Renewal workflow

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationMapper.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Engines.Transformation/PortalInvitations/PortalInvitationTransformationEngine.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationHandlers.cs, src/ECER.Resources.Documents/Applications/ApplicationRepositoryMapper.cs, src/ECER.Resources.Documents/Applications/IApplicationRepository.cs, src/ECER.Tests/Integration/Resources/Applications/ApplicationRepositoryTests.cs, src/ECER.Tests/Unit/ApplicationRenewalValidationEngineTests.cs, src/ECER.Tests/Unit/ApplicationSubmissionValidationEngineTests.cs, src/ECER.Tests/Unit/LabourMobilityApplicationSubmissionValidationEngineTests.cs
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-4795: Fixed Transcript status option problem

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantLaborMobilityRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearLaborMobilityRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearLaborMobilityRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/SpecializedCertificationOptions.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/TransferCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
- Content pages and pathways for Labour Mobility applications
- [ECER-1780](https://eccbc.atlassian.net/browse/ECER-1780)
- [ECER-4693](https://eccbc.atlassian.net/browse/ECER-4693)
- [ECER-4694](https://eccbc.atlassian.net/browse/ECER-4694)
=> ECER-4694: Labour Mobility Requirements 

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/ConfigurationEndpoints.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/ConfigurationMapper.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/api/configuration.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/MessageListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/TransferCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Transfer.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/config.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/functions.ts, src/ECER.Managers.Admin.Contract/Metadatas/Contract.cs, src/ECER.Managers.Admin/MetadataHandlers.cs, src/ECER.Managers.Admin/MetadataMapper.cs, src/ECER.Resources.Documents/MetadataResources/IMetadataResourceRepository.cs, src/ECER.Resources.Documents/MetadataResources/MetadataResourceRepository.cs, src/ECER.Resources.Documents/MetadataResources/MetadataResourceRepositoryMapper.cs, src/ECER.Tests/Integration/RegistryApi/ConfigurationTests.cs
- Certification comparison back-end pieces
- Certification comparison front-end pieces
- ECER-4688
- ECER-4666
Objects stored in the Dynamics side needed to be grouped to be able to be shown in the portal side
=> Stories/ecer 4688: Certification Comparison Table Front-end and Back-end pieces

.sonarcloud.properties
---
---
- etc.
- ECER-{###}
- etc.
=> should no longer check our cypress checks for duplicate code

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryCharacterReferenceListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ManageWorkExperienceReferenceListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/NavigationBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WorkExperienceReferenceCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceEvaluation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/functions.ts
ECER-3794: Null firstname on front app fixed
- ECER-{3794}
- etc.
=> ECER-3794: null problem in firstname resolved in FE application

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummaryCharacterReferenceListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ManageWorkExperienceReferenceListItem.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/NavigationBar.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/WorkExperienceReferenceCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/NewUser.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/Reference.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceEvaluation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/functions.ts
ECER-3794: front-end null firstname problem commit
- ECER-{###}
- etc.
=> ECER-3794: front-end null firstname problem commit

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationType.vue
https://eccbc.atlassian.net/browse/ECER-4852
- etc.
- ECER-{###}
- etc.
=> ecer-4852 typo fix

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/.gitignore, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress.config.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/newCertifications/newECE5YearCertification.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/newCertifications/newECE5YearPlusITECertification.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/newCertifications/newECE5YearPlusITEandSNECertification.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/newCertifications/newECE5YearPlusSNECertification.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/newCertifications/newECEAssistantCertification.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/newCertifications/newECEOneYearCertification.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/e2e/ui/z_Cleanup/z_logout.cy.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/support/commands.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/cypress/support/e2e.ts
- Fix Flaky test runs on cypress cloud
- ECER-4253
=> Fix Flaky test runs on cypress cloud

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationRequirements.vue
- [ECER-4869](https://eccbc.atlassian.net/browse/ECER-4869)
=> ECER-4869: Fix LM application flow setup

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/LookupCertification.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RegistrantCard.vue
---
---
- etc.
- ECER-{###}
- etc.
=> ECER-3590: Context update

src/ECER.Utilities.DataverseSdk/Queries/Join2QueryExpressionBuilder.cs
Unnecessary log removed from join2query builder
- ECER-4801
- etc.
=> ECER-4801: Unnecessary log removed from join2query builder

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationType.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue
- Remove LM question from certification type selection
- Cleanup non-LM application requirements 
- [ECER-4107](https://eccbc.atlassian.net/browse/ECER-4107)
=> ECER-4107: Remove LM question from certification type selection

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/utils/formRules.ts
- Adjust regex
- [ECER-4551](https://eccbc.atlassian.net/browse/ECER-4551)
=> ECER-4551: Tighten up email regex pattern

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearContent.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearContent.vue
- Copy adjustment
- [ECER-4664](https://eccbc.atlassian.net/browse/ECER-4664)
=> ECER-4664: Copy adjustment

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantLaborMobilityRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearLaborMobilityRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearLaborMobilityRequirements.vue
---
---
https://eccbc.atlassian.net/browse/ECER-4947
- etc.
- ECER-{###}
- etc.
=> ecer-4947 content change

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificateInformation.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificateInformationPreview.vue
---
---
- etc.
- ECER-{###}
- etc.
=> Make certificate number optional

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Transfer.vue
---
---
https://eccbc.atlassian.net/browse/ECER-4946
- etc.
- ECER-{###}
- etc.
=> ecer-4946 rework adding periods at the end of the province

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue
ECER-4927: Application summary page now has fresh previous name data to show
- etc.
- ECER-4927
- etc.
=> ECER-4927: Profile information set in application summary

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearLaborMobilityRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRenewalRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEIteRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECESneRegistrantRequirements.vue
---
---
https://eccbc.atlassian.net/browse/ECER-4951
- etc.
- ECER-{###}
- etc.
=> ecer-4951 content update

.sonarcloud.properties, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Alert.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationList.stories.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Certifications.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/certification.ts
- Other certifications page
- Block button on dashboard
- [ECER-4864](https://eccbc.atlassian.net/browse/ECER-4864)
=> ECER-4864: My other certifications

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationCard.stories.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationList.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RenewAction.stories.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/RenewAction.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
- Hide renewal path when applicant has ongoing application
- Fix text and button mismatch for can/can't renew for ECE Assistant
- Style other certifications button
=> Renewal fixes

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceCertificateInformationPreview.vue
https://eccbc.atlassian.net/browse/ECER-4211 
- just moved some text outside of the preview box. 
- ECER-{###}
- etc.
=> ecer-4211 setting non-editable fields outside of the preview card

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/Applications/ApplicationsEndpoints.cs, src/ECER.Engines.Validation/Applications/ApplicationRenewalValidationEngine.cs, src/ECER.Engines.Validation/Applications/RenewalValidationConditions/EceAssistant.cs, src/ECER.Engines.Validation/Applications/RenewalValidationConditions/FiveYears.cs, src/ECER.Engines.Validation/Applications/RenewalValidationConditions/OneYear.cs, src/ECER.Managers.Registry.Contract/Applications/Contract.cs, src/ECER.Managers.Registry/ApplicationMapper.cs, src/ECER.Tests/Unit/ApplicationRenewalValidationEngineTests.cs
ECER-4252: Multiple Certifications Renewal Backend
- ECER-4252
- etc.
=> ECER-4252: Backend piece for multiple certificates renewal

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/pages/Dashboard.vue
---
---
https://eccbc.atlassian.net/browse/ECER-5057
- etc.
- ECER-{###}
- etc.
=> removing section from dashboard

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Breadcrumb.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/character-reference-wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/preview-form-assistant-and-one-year-labor-mobility.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/preview-form-assistant-and-one-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/preview-form-five-year-labor-mobility.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/preview-form-five-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/preview-form-ite-sne.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/preview-form-labor-mobility-assistant-and-one-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/preview-form-labor-mobility-five-year.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/work-experience-reference-400-hours-wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/work-experience-reference-wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts
- Breadcrumbs styling
- Content update (Preview -> Review)
- [ECER-2141](https://eccbc.atlassian.net/browse/ECER-2141)
- [ECER-1803](https://eccbc.atlassian.net/browse/ECER-1803)
=> ECER-2141/ECER-1803: 

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceCharacterReferenceDeclaration.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/reference/inputs/EceWorkExperienceReferenceDeclaration.vue
---
---
https://eccbc.atlassian.net/browse/ECER-5238?actionerId=712020%3A547188e4-38b6-4517-9c7d-df8d8faefe2c&sourceType=assign
- etc.
- ECER-{###}
- etc.
=> ecer-5238 typo update

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEIteRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEOneYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECESneRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/SpecializedCertificationOptions.vue
ECER-5186: Brief description of the changes
- Change references to SNE education to remove “early childhood”
- Change references to all education to remove “training”
- etc.
- ECER-5186
=> Stories/ecer-5186: References Changed

.github/workflows/deploy-to-dev.yaml
---
---
- etc.
- ECER-{###}
- etc.
=> quick fix to add psp-portal to deploy to dev

src/ECER.Resources.Documents/MetadataResources/MetadataResourceRepository.cs
ECER-{###}: LM records filtered by active status
- etc.
- ECER-{###}
- etc.
=> LM records filtered by active status

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/Breadcrumb.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/IcraEligibilityRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
---
---
https://eccbc.atlassian.net/browse/ECER-4779 
- etc.
- ECER-{###}
- etc.
=> ecer-4779 eligibility requirements page

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/IcraEligibilityCard.vue
https://eccbc.atlassian.net/browse/ECER-5366
- etc.
- ECER-{###}
- etc.
=> ecer-5366 eligibility card

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts
---
---
- etc.
- ECER-{###}
- etc.
=> ecer-5413 character reference bug

src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/ICRA/ICRAEligibilitiesEndpoints.cs, src/ECER.Clients.RegistryPortal/ECER.Clients.RegistryPortal.Server/ICRA/ICRAEligibilityMapper.cs, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/EceEmploymentExperienceCard.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEmploymentExperience.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/inputs/EceEmploymentExperiencePreview.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/config/employment-experience-form.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/icra.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/store/wizard.ts, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/types/openapi.d.ts, src/ECER.Managers.Registry.Contract/ICRA/Contract.cs, src/ECER.Managers.Registry/ICRAEligibilityMapper.cs, src/ECER.Resources.Documents/ICRA/ICRAChildren/EmploymentReferences.cs, src/ECER.Resources.Documents/ICRA/ICRARepository.cs, src/ECER.Resources.Documents/ICRA/ICRARepositoryMapper.cs, src/ECER.Resources.Documents/ICRA/IICRARepository.cs, src/ECER.Tests/Integration/RegistryApi/IcraTests.cs
ECER-4782: Work experience references for ICRA eligibility object
- Workexperience references backend piece for ICRA eligibility object
- Workexperience references frontend piece for ICRA eligibility object
- etc.
- ECER-4782
- etc.
=> Stories/ecer 4782: Work experience references for ICRA eligibility object

src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEAssistantRenewalRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearLaborMobilityRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRegistrantRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRenewalRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ECEFiveYearRequirements.vue, src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/EducationList.vue
- [ECER-5348](https://eccbc.atlassian.net/browse/ECER-5348)
=> ECER-5348: Content update
